var _yt_www={};(function(g){var window=this;var baa,caa,sa,Ba,bb,cb,kaa,fb,gb,laa,ob,maa,vb,Hb,Xb,vaa,Kc,yaa,zaa,xaa,pd,Aaa,zd,Gd,Id,Jd,Ld,Nd,Daa,Qd,Dd,Od,Pd,Ad,Fd,Kd,Hd,Rd,Faa,de,ge,je,le,te,ue,Laa,De,Maa,Ne,Te,Se,Naa,jf,kf,Oaa,sf,tf,Paa,wf,Af,yf,xf,Qaa,Ff,Hf,If,Jf,Mf,Pf,Of,Lf,Nf,Qf,Cf,Gf,Waa,Rf,Sf,Xaa,Yaa,Yf,$f,bg,fg,eg,gg,ig,Zaa,$aa,aba,ng,rg,sg,tg,wg,xg,yg,gba,hba,og,qg,mg,fba,pg,Bg,Cg,pa,aaa;g.ba=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.ca=function(a){return void 0!==a};
g.l=function(a,b,c){a=a.split(".");c=c||g.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.m=function(a,b){for(var c=a.split("."),d=b||g.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.fa=function(){};
g.ga=function(a){a.getInstance=function(){return a.Bc?a.Bc:a.Bc=new a}};
g.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ia=function(a){return"array"==g.ha(a)};
g.ka=function(a){var b=g.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.la=function(a){return"string"==typeof a};
g.ma=function(a){return"number"==typeof a};
g.na=function(a){return"function"==g.ha(a)};
g.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.qa=function(a){return a[pa]||(a[pa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.n=function(a,b,c){g.n=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.n.apply(null,arguments)};
g.ra=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.q=function(a,b){function c(){}
c.prototype=b.prototype;a.N=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var k=Array(arguments.length-2),p=2;p<arguments.length;p++)k[p-2]=arguments[p];return b.prototype[c].apply(a,k)}};
sa=function(a){sa[" "](a);return a};
g.ua=function(a,b){try{return sa(a[b]),!0}catch(c){}return!1};
g.va=function(a,b){return 0==a.lastIndexOf(b,0)};
g.wa=function(a){return(0,window.encodeURIComponent)(String(a))};
g.xa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.ya=function(a,b){return-1!=a.indexOf(b)};
g.za=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
g.Ca=function(a,b){for(var c=0,d=(0,g.Aa)(String(a)).split("."),e=(0,g.Aa)(String(b)).split("."),f=Math.max(d.length,e.length),k=0;0==c&&k<f;k++){var p=d[k]||"",r=e[k]||"",B=RegExp("(\\d*)(\\D*)","g"),C=RegExp("(\\d*)(\\D*)","g");do{var N=B.exec(p)||["","",""],V=C.exec(r)||["","",""];if(0==N[0].length&&0==V[0].length)break;c=Ba(0==N[1].length?0:(0,window.parseInt)(N[1],10),0==V[1].length?0:(0,window.parseInt)(V[1],10))||Ba(0==N[2].length,0==V[2].length)||Ba(N[2],V[2])}while(0==c)}return c};
Ba=function(a,b){return a<b?-1:a>b?1:0};
g.Da=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
g.Ea=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
g.Fa=function(a){var b=g.la(void 0)?g.za(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
g.Ga=function(a){return a};
g.Ja=function(a,b,c){b=g.Ha(a,b,c);return 0>b?null:g.la(a)?a.charAt(b):a[b]};
g.Ha=function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};
g.La=function(a,b){return 0<=(0,g.Ka)(a,b)};
g.Na=function(a,b){var c=(0,g.Ka)(a,b),d;(d=0<=c)&&g.Ma(a,c);return d};
g.Ma=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.Oa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Pa=function(a){return function(){return a}};
g.Qa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
g.Ra=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Sa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Ta=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Ua=function(a,b){b in a&&delete a[b]};
g.Va=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Wa=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.Ya=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Xa.length;f++)c=Xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.$a=function(a){return g.ya(g.Za,a)};
bb=function(){return g.$a("Opera")||g.$a("OPR")};
cb=function(){return(g.$a("Chrome")||g.$a("CriOS"))&&!bb()&&!g.$a("Edge")};
g.db=function(a){g.da.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.da.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.$a("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.n)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.$a("Trident")&&!g.$a("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.ca(c.next)){c=c.next;var a=c.ep;c.ep=null;a()}};
return function(a){d.next={ep:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.da.setTimeout(a,0)}};
g.eb=function(a,b,c){this.G=c;this.C=a;this.D=b;this.B=0;this.A=null};
fb=function(){this.B=this.A=null};
gb=function(){this.next=this.scope=this.se=null};
g.nb=function(a,b){ib||laa();jb||(ib(),jb=!0);var c=kb,d=lb.get();d.set(a,b);c.B?c.B.next=d:c.A=d;c.B=d};
laa=function(){if(g.da.Promise&&g.da.Promise.resolve){var a=g.da.Promise.resolve(void 0);ib=function(){a.then(ob)}}else ib=function(){var a=ob;
!g.na(g.da.setImmediate)||g.da.Window&&g.da.Window.prototype&&!g.$a("Edge")&&g.da.Window.prototype.setImmediate==g.da.setImmediate?(pb||(pb=kaa()),pb(a)):g.da.setImmediate(a)}};
ob=function(){for(var a=null;a=kb.remove();){try{a.se.call(a.scope)}catch(b){g.db(b)}lb.put(a)}jb=!1};
g.qb=function(){this.Tc=this.Tc;this.Gb=this.Gb};
g.tb=function(a,b){g.rb(a,g.ra(g.sb,b))};
g.rb=function(a,b){a.Tc?b.call(void 0):(a.Gb||(a.Gb=[]),a.Gb.push(g.ca(void 0)?(0,g.n)(b,void 0):b))};
g.sb=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.ub=function(a){g.qb.call(this);this.D=1;this.B=[];this.C=0;this.A=[];this.xd={};this.G=Boolean(a)};
maa=function(a,b,c){g.nb(function(){a.apply(b,c)})};
g.xb=function(a){vb(g.wb,arguments)};
g.t=function(a,b){return a in g.wb?g.wb[a]:b};
g.zb=function(a,b){g.na(a)&&(a=g.yb(a));return window.setTimeout(a,b)};
g.Ab=function(a,b){g.na(a)&&(a=g.yb(a));return window.setInterval(a,b)};
g.Bb=function(a){window.clearTimeout(a)};
g.Cb=function(a){window.clearInterval(a)};
g.yb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.Db(b),b;}}:a};
g.Db=function(a,b){var c=g.m("yt.logging.errors.log");c?c(a,b):(c=g.t("ERRORS",[]),c.push([a,b]),g.xb("ERRORS",c))};
g.Fb=function(a){return a in g.Eb};
g.Gb=function(a,b,c){var d=b||{};if(a=a in g.Eb?g.Eb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});
return a};
vb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.Mb=function(a,b,c){var d=Hb();if(d){var e=d.subscribe(a,function(){if(!Ib||Ib!=e){var d=arguments,k=function(){Jb[e]&&b.apply(c||window,d)};
try{Kb[a]?k():g.zb(k,0)}catch(p){g.Db(p)}}},c);
Jb[e]=!0;Lb[a]||(Lb[a]=[]);Lb[a].push(e);return e}return 0};
g.Nb=function(a){var b=Hb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.u)(a,function(a){b.unsubscribeByKey(a);delete Jb[a]}))};
g.v=function(a,b){var c=Hb();return c?c.publish.apply(c,arguments):!1};
g.Ob=function(a,b){Kb[a]=!0;var c=Hb(),c=c?c.publish.apply(c,arguments):!1;Kb[a]=!1;return c};
Hb=function(){return g.m("yt.pubsub.instance_")};
g.Pb=function(){return!!g.m("yt.scheduler.instance")};
g.Qb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.m("yt.scheduler.instance.addJob");return c?c(a,0,b):void 0===b?(a(),window.NaN):g.zb(a,b||0)};
g.Rb=function(a,b){return g.Qb(a,b)};
g.Sb=function(a){var b=g.m("yt.scheduler.instance.cancelJob");b?b(a):g.Bb(a)};
g.Tb=function(a){for(var b=0,c=a.length;b<c;b++)g.Sb(a[b])};
g.Ub=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.H=d?g.yb(d):null;this.G=e?g.yb(e):null;this.D=[];this.A=this.B=0};
g.Vb=function(a){g.Sb(a.B);a.B=g.Rb((0,g.n)(a.init,a))};
g.Yb=function(a){a.name in Wb&&Xb(a.name);Wb[a.name]={reqs:[],disable:(0,g.n)(a.disable,a)};(0,g.u)(a.deps,function(b){if(!(b in Wb))throw Error("Module "+b+" required by "+a.name);Wb[b].reqs.push(a.name)});
a.enable()};
Xb=function(a){if(a in Wb){var b=Wb[a];(0,g.u)(b.reqs,function(a){Xb(a)});
try{b.disable()}catch(c){}delete Wb[a]}};
g.$b=function(){this.A="";this.B=Zb};
g.ac=function(a){return a instanceof g.$b&&a.constructor===g.$b&&a.B===Zb?a.A:"type_error:Const"};
g.cc=function(){this.A="";this.B=bc};
g.dc=function(a){return a instanceof g.cc&&a.constructor===g.cc&&a.B===bc?a.A:"type_error:SafeStyle"};
g.ec=function(a){var b=new g.cc;b.A=a;return b};
g.gc=function(){this.A="";this.B=fc};
g.hc=function(a){return a instanceof g.gc&&a.constructor===g.gc&&a.B===fc?a.A:"type_error:SafeUrl"};
g.jc=function(a){if(a instanceof g.gc)return a;a=a.Lf?a.ue():String(a);naa.test(a)||(a="about:invalid#zClosurez");return g.ic(a)};
g.ic=function(a){var b=new g.gc;b.A=a;return b};
g.lc=function(){this.A="";this.B=kc};
g.mc=function(a){return a instanceof g.lc&&a.constructor===g.lc&&a.B===kc?a.A:"type_error:TrustedResourceUrl"};
g.oc=function(){this.A="";this.C=nc;this.B=null};
g.pc=function(a){return a instanceof g.oc&&a.constructor===g.oc&&a.C===nc?a.A:"type_error:SafeHtml"};
g.rc=function(a){if(a instanceof g.oc)return a;var b=null;a.lm&&(b=a.qg());a=g.xa(a.Lf?a.ue():String(a));return g.qc(a,b)};
g.uc=function(a,b,c){if(!sc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in oaa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return g.tc(a,b,c)};
g.vc=function(a){function b(a){g.ia(a)?(0,g.u)(a,b):(a=g.rc(a),d+=g.pc(a),a=a.qg(),0==c?c=a:0!=a&&c!=a&&(c=null))}
var c=0,d="";(0,g.u)(arguments,b);return g.qc(d,c)};
g.qc=function(a,b){var c=new g.oc;c.A=a;c.B=b;return c};
g.tc=function(a,b,c){var d=null,e="<"+a;if(b)for(var f in b){if(!sc.test(f))throw Error('Invalid attribute name "'+f+'".');var k=b[f];if(null!=k){var p,r=a;p=f;if(k instanceof g.$b)k=g.ac(k);else if("style"==p.toLowerCase()){if(!g.oa(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+" given: "+k);if(!(k instanceof g.cc)){var r="",B=void 0;for(B in k){if(!/^[-_a-zA-Z0-9]+$/.test(B))throw Error("Name allows only [-_a-zA-Z0-9], got: "+B);var C=
k[B];if(null!=C){if(C instanceof g.$b)C=g.ac(C),g.Ga(!/[{;}]/.test(C));else if(paa.test(C)){for(var N=!0,V=!0,ea=0;ea<C.length;ea++){var ta=C.charAt(ea);"'"==ta&&V?N=!N:'"'==ta&&N&&(V=!V)}N&&V||(C="zClosurez")}else C="zClosurez";r+=B+":"+C+";"}}k=r?g.ec(r):qaa}k=g.dc(k)}else{if(/^on/i.test(p))throw Error('Attribute "'+p+'" requires goog.string.Const value, "'+k+'" given.');if(p.toLowerCase()in raa)if(k instanceof g.lc)k=g.mc(k);else if(k instanceof g.gc)k=g.hc(k);else if(g.la(k))k=g.jc(k).ue();else throw Error('Attribute "'+
p+'" on tag "'+r+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+k+'" given.');}k.Lf&&(k=k.ue());p=p+'="'+g.xa(String(k))+'"';e=e+(" "+p)}}null!=c?g.ia(c)||(c=[c]):c=[];!0===saa[a.toLowerCase()]?e+=">":(d=g.vc(c),e+=">"+g.pc(d)+"</"+a+">",d=d.qg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return g.qc(e,d)};
g.wc=function(a,b){a.innerHTML=g.pc(b)};
g.xc=function(a,b){var c;c=b instanceof g.gc?b:g.jc(b);a.href=g.hc(c)};
g.w=function(a,b){return a?a.dataset?a.dataset[g.yc(b)]:a.getAttribute("data-"+b):null};
g.zc=function(a,b){return a?a.dataset?g.yc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};
g.yc=function(a){return Ac[a]||(Ac[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.Cc=function(a,b){var c=g.Bc(a);window.spf.script.load(a,c,b)};
g.Dc=function(a,b){var c=g.Bc(a);window.spf.script.ignore(c,b)};
g.Bc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(taa,""),b=b.replace(uaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.Ec=function(a,b){this.x=g.ca(a)?a:0;this.y=g.ca(b)?b:0};
g.Fc=function(){return g.$a("iPhone")&&!g.$a("iPod")&&!g.$a("iPad")};
vaa=function(){var a=g.Za;if(g.Gc)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.Hc)return/Edge\/([\d\.]+)/.exec(a);if(g.Ic)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Jc)return/WebKit\/(\S+)/.exec(a)};
Kc=function(){var a=g.da.document;return a?a.documentMode:void 0};
g.Nc=function(a){return Lc[a]||(Lc[a]=0<=g.Ca(g.Mc,a))};
g.Pc=function(a){return Number(g.Oc)>=a};
g.x=function(a){return g.la(a)?window.document.getElementById(a):a};
g.Qc=function(a){return g.la(a)?window.document.getElementById(a):a};
g.y=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=g.Rc(window.document,"*",a,b)[0];return d||null};
g.Rc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,k;k=a[f];f++)b==k.nodeName&&(d[e++]=k);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;k=a[f];f++)b=k.className,"function"==typeof b.split&&g.La(b.split(/\s+/),c)&&(d[e++]=k);d.length=e;return d}return a};
g.Tc=function(a,b){g.Ra(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Sc.hasOwnProperty(d)?a.setAttribute(Sc[d],b):g.va(d,"aria-")||g.va(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.Vc=function(a){var b=g.Uc(a);a=a.parentWindow||a.defaultView;return g.Ic&&g.Nc("10")&&a.pageYOffset!=b.scrollTop?new g.Ec(b.scrollLeft,b.scrollTop):new g.Ec(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Uc=function(a){return a.scrollingElement?a.scrollingElement:!g.Jc&&g.Wc(a)?a.documentElement:a.body||a.documentElement};
g.Zc=function(a,b,c){return g.Xc(window.document,arguments)};
g.Xc=function(a,b){var c=b[0],d=b[1];if(!waa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.xa(d.name),'"');if(d.type){c.push(' type="',g.xa(d.type),'"');var e={};g.Ya(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.la(d)?c.className=d:g.ia(d)?c.className=d.join(" "):g.Tc(c,d));2<b.length&&g.$c(a,c,b,2);return c};
g.$c=function(a,b,c,d){function e(c){c&&b.appendChild(g.la(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var f=c[d];!g.ka(f)||g.oa(f)&&0<f.nodeType?e(f):(0,g.u)(xaa(f)?g.Oa(f):f,e)}};
g.Wc=function(a){return"CSS1Compat"==a.compatMode};
g.ad=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.bd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.cd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
yaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
zaa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.ed=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
xaa=function(a){if(a&&"number"==typeof a.length){if(g.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.na(a))return"function"==typeof a.item}return!1};
g.fd=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.gd=function(a,b,c,d,e,f,k){var p="";a&&(p+=a+":");c&&(p+="//",b&&(p+=b+"@"),p+=c,d&&(p+=":"+d));e&&(p+=e);f&&(p+="?"+f);k&&(p+="#"+k);return p};
g.hd=function(a){return a?(0,window.decodeURI)(a):a};
g.jd=function(a,b){return b.match(g.id)[a]||null};
g.kd=function(a){return g.hd(g.jd(3,a))};
g.ld=function(a){a=a.match(g.id);return g.gd(null,null,null,null,a[5],a[6],a[7])};
g.md=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.nd=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.od=function(a,b,c){if(g.ia(b))for(var d=0;d<b.length;d++)g.od(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.wa(b))};
pd=function(a,b){for(var c in b)g.od(c,b[c],a);return a};
g.qd=function(a){a=pd([],a);a[0]="";return a.join("")};
g.rd=function(a,b){return g.nd(pd([a],b))};
g.sd=function(a,b,c){a&&(c?a&&(a=g.Zc("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.ed(a).body.appendChild(a)):Aaa(a,b))};
g.td=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.sd(a,void 0)}catch(b){g.sd(a,void 0)}};
Aaa=function(a,b){var c=new window.Image,d=""+Baa++;ud[d]=c;c.onload=c.onerror=function(){b&&ud[d]&&b();delete ud[d]};
c.src=a};
g.vd=function(a,b){this.version=a;this.args=b};
g.wd=function(a,b){this.topic=a;this.tf=b};
g.yd=function(a,b){var c=g.xd();return c?c.publish.call(c,a.toString(),a,b):!1};
g.xd=function(){return g.m("yt.pubsub2.instance_")};
zd=function(a){g.vd.call(this,1,arguments)};
g.Ed=function(a,b,c){Ad(c)[a]=b||(0,g.Bd)();b||Cd(a);Dd(!1,c)};
Gd=function(a,b){Fd(void 0).yt_sts=a;g.Ed("_start",b,void 0)};
Id=function(a){Hd(a);Caa();g.l("yt.timing.pingSent_",!1,void 0)};
Jd=function(a){a=Ad(a);if(a.aft)return a.aft;for(var b=g.t("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
Ld=function(a,b){var c=b||Kd(void 0).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};
Nd=function(a){return Math.round(Md.timing.navigationStart+a)};
Daa=function(a){var b=window.location.protocol,c=Md.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=Nd(d.startTime),a.wfce=Nd(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=Nd(c.startTime),a.wffe=Nd(c.responseEnd))};
Qd=function(a){var b=Ad(a),c=Kd(a).span,d=Fd(a),e=g.m("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))Od(e),Id(a)}else{var f=g.t("CSI_SERVICE_NAME","youtube"),e={v:2,s:f,action:g.t("TIMING_ACTION",void 0)};if(Md.now&&Md.timing){var k=Md.timing.navigationStart+Md.now(),k=Math.round((0,g.Bd)()-k);d.yt_hrd=k}var k=g.t("TIMING_INFO",{}),p;for(p in k)d[p]=k[p];p=d.srt;delete d.srt;var r;p||0===p||(r=Md.timing||{},p=Math.max(0,r.responseStart-r.navigationStart),(0,window.isNaN)(p)&&d.pt&&(p=d.pt));if(p||
0===p)d.srt=p;d.h5jse&&(k=window.location.protocol+g.m("ytplayer.config.assets.js"),(k=Md.getEntriesByName?Md.getEntriesByName(k)[0]:null)?d.h5jse=Math.round(d.h5jse-k.responseEnd):delete d.h5jse);b.aft=Jd(a);k=b._start;if("cold"==d.yt_lt){r||(r=Md.timing||{});var B;a:if(B=r,B.msFirstPaint)B=Math.max(0,B.msFirstPaint);else{var C=window.chrome;if(C&&(C=C.loadTimes,g.na(C))){var C=C(),N=1E3*Math.min(C.requestTime||window.Infinity,C.startLoadTime||window.Infinity),N=window.Infinity===N?0:B.navigationStart-
N;B=Math.max(0,Math.round(1E3*C.firstPaintTime+N)||0);break a}B=0}0<B&&B>k&&(b.fpt=B);Ld(r,c);Md.getEntriesByType&&Daa(b)}C=Ad(a);r=C.pbr;B=C.vc;C=C.pbs;r&&B&&C&&r<B&&B<C&&1==Fd(a).yt_vis&&"youtube"==f&&(Fd(a).yt_lt="hot_bg",f=b.vc,r=b.pbs,delete b.aft,c.aft=Math.round(r-f));(f=g.t("PREVIOUS_ACTION"))&&(d.pa=f);d.p=g.t("CLIENT_PROTOCOL")||"unknown";d.t=g.t("CLIENT_TRANSPORT")||"unknown";window.navigator&&window.navigator.sendBeacon&&(d.ba=1);for(var V in d)"_"!=V.charAt(0)&&(e[V]=d[V]);b.ps=(0,g.Bd)();
d={};V=[];for(var ea in b)"_"!=ea.charAt(0)&&(B=Math.max(Math.round(b[ea]-k),0),d[ea]=B,V.push(ea+"."+B));e.rt=V.join(",");b=e;ea=[];for(var ta in c)"_"!=ta.charAt(0)&&ea.push(ta+"."+c[ta]);b.it=ea.join(",");(ta=g.m("ytdebug.logTiming"))&&ta(e,d,c);Id(a);g.t("EXP_DEFER_CSI_PING")?(Pd(),g.l("yt.timing.deferredPingArgs_",e,void 0),a=g.zb(Pd,0),g.l("yt.timing.deferredPingTimer_",a,void 0)):Od(e);g.yd(Eaa,new zd(d.aft+(p||0)))}};
Dd=function(a,b){var c=g.t("TIMING_ACTION",void 0),d=Ad(b);if(g.m("yt.timing.ready_")&&c&&d._start&&Jd(b)){var c=!0,e=g.t("TIMING_WAIT",[]);if(!a&&e.length)for(var f=0,k=e.length;f<k;++f)if(!(e[f]in d)){c=!1;break}(c||b)&&Qd(b)}};
Od=function(a){if(g.t("DEBUG_CSI_DATA")){var b=g.m("yt.timing.csiData");b||(b=[],g.l("yt.timing.csiData",b,void 0));b.push({page:window.location.href,time:new Date,args:a})}g.t("EXP_DEFER_CSI_PING")&&(g.Bb(g.m("yt.timing.deferredPingTimer_")),g.l("yt.timing.deferredPingArgs_",null,void 0));var c="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",b="",d;for(d in a)b+="&"+d+"="+a[d];a=c+"?"+b.substring(1);b=g.t("CSI_LOG_WITH_YT")?"/csi_204?"+b.substring(1):null;
window.navigator&&window.navigator.sendBeacon?(g.td(a),b&&g.td(b)):(g.sd(a),b&&g.sd(b));g.l("yt.timing.pingSent_",!0,void 0)};
Pd=function(a){if(g.t("EXP_DEFER_CSI_PING")){var b=g.m("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),Od(b))}};
Ad=function(a){return Kd(a).tick};
Fd=function(a){return Kd(a).info};
Kd=function(a){return g.m("ytcsi."+(a||"")+"data_")||Hd(a)};
Hd=function(a){var b={tick:{},span:{},info:{}};g.l("ytcsi."+(a||"")+"data_",b,void 0);return b};
Rd=function(a){g.m("yt.timing.pingSent_")||(g.Ed("aa"),Fd(void 0).ap=1,Fd(void 0).yt_fss=a,Qd())};
Faa=function(a){a=g.Sd(a);return g.Td(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
g.Td=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
g.Sd=function(a){a=g.kd(a);return null===a?null:a.split(".").reverse()};
g.Ud=function(a,b){g.sd("/gen_204?"+a,b)};
g.Vd=function(a){if(a.classList)return a.classList;a=a.className;return g.la(a)&&a.match(/\S+/g)||[]};
g.z=function(a,b){return a.classList?a.classList.contains(b):g.La(g.Vd(a),b)};
g.A=function(a,b){a.classList?a.classList.add(b):g.z(a,b)||(a.className+=0<a.className.length?" "+b:b)};
g.D=function(a,b){a.classList?a.classList.remove(b):g.z(a,b)&&(a.className=(0,g.Wd)(g.Vd(a),function(a){return a!=b}).join(" "))};
g.Xd=function(a,b,c){c?g.A(a,b):g.D(a,b)};
g.Yd=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.u)(a.childNodes,function(a){b.appendChild(g.Yd(a))}):b.innerHTML=a.innerHTML;
return b};
g.Zd=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Gaa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.Sm=a.pageX;this.Tm=a.pageY}};
g.ae=function(a,b,c,d){return g.Ta(g.$d,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.E=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.ae(a,b,c,d);if(e)return e;var e=++be.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=f?function(d){d=new g.Zd(d);if(!g.fd(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.Zd(b);
b.currentTarget=a;return c.call(a,b)};
k=g.yb(k);g.$d[e]=[a,b,c,k,d];a.addEventListener?"mouseenter"==b&&f?a.addEventListener("mouseover",k,d):"mouseleave"==b&&f?a.addEventListener("mouseout",k,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",k,d):a.addEventListener(b,k,d):a.attachEvent("on"+b,k);return e};
g.ce=function(a){a&&("string"==typeof a&&(a=[a]),(0,g.u)(a,function(a){if(a in g.$d){var c=g.$d[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete g.$d[a]}}))};
g.ee=function(){if(null==g.m("_lact",window)){var a=(0,window.parseInt)(g.t("LACT"),10),a=(0,window.isFinite)(a)?(0,g.Bd)()-Math.max(a,0):-1;g.l("_lact",a,window);-1==a&&de();g.E(window.document,"keydown",de);g.E(window.document,"keyup",de);g.E(window.document,"mousedown",de);g.E(window.document,"mouseup",de);g.Mb("page-mouse",de);g.Mb("page-scroll",de);g.Mb("page-resize",de)}};
de=function(){null==g.m("_lact",window)&&(g.ee(),g.m("_lact",window));var a=(0,g.Bd)();g.l("_lact",a,window);g.v("USER_ACTIVE")};
g.fe=function(){var a=g.m("_lact",window);return null==a?-1:Math.max((0,g.Bd)()-a,0)};
ge=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Wa(Haa);this.assets=a.assets||{};this.attrs=a.attrs||g.Wa(Iaa);this.params=a.params||g.Wa(Jaa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.he=function(a){a instanceof ge||(a=new ge(a));return a};
je=function(){return null!=g.ie};
g.ke=function(){return g.ie?g.ie.invoke():null};
le=function(){return(0,window.parseInt)(g.t("DCLKSTAT",0),10)};
g.me=function(a,b){this.A=a;this.B=b};
g.ne=function(a){this.A=a};
g.pe=function(a){a=(a.A.cookie||"").split(g.oe);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.re=function(a,b,c,d){g.qe.set(""+a,b,c,"/",d||"youtube.com")};
g.se=function(a,b){return g.qe.get(""+a,b)};
g.ve=function(a,b,c){var d=g.t("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.kd(window.location.href);e&&d.push(e);e=g.kd(a);if(g.La(d,e)||!e&&g.va(a,"/"))if(a=g.ld(a),a=g.md(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(te(a,b,c),ue(b))):(te(a,b),ue(b))};
te=function(a,b,c){a=g.t("SMALLER_SESSION_TEMPDATA_NAME")?"ST-"+g.Da(a).toString(36):"s_tempdata-"+g.Da(a);c=c||5;b=b?g.qd(b):"";g.re(a,b,c)};
ue=function(a){if(a){a=a.itct||a.ved;var b=g.m("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.me(a))}};
g.we=function(a,b,c){c=c||"";g.xc(window.location,g.rd(a,b||{})+c)};
g.xe=function(a,b){b&&g.ve(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.we(a)};
g.ye=function(a,b,c){var d=g.t("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.ve(a,b);if(c)return!1;g.xe(a);return!0};
g.ze=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.Wf=!1;this.Fu=!0};
g.Ae=function(a,b){g.ze.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.Xm=!1;this.Cb=null;a&&this.init(a,b)};
g.Ce=function(a){return!(!a||!a[g.Be])};
Laa=function(a,b,c,d,e){this.listener=a;this.A=null;this.src=b;this.type=c;this.eh=!!d;this.sd=e;this.key=++Kaa;this.Jg=this.Di=!1};
De=function(a){a.Jg=!0;a.listener=null;a.A=null;a.src=null;a.sd=null};
g.Ee=function(a){this.src=a;this.A={};this.B=0};
g.Ge=function(a,b,c,d,e,f){var k=b.toString();b=a.A[k];b||(b=a.A[k]=[],a.B++);var p=g.Fe(b,c,e,f);-1<p?(a=b[p],d||(a.Di=!1)):(a=new Laa(c,a.src,k,!!e,f),a.Di=d,b.push(a));return a};
g.He=function(a,b){var c=b.type;if(!(c in a.A))return!1;var d=g.Na(a.A[c],b);d&&(De(b),0==a.A[c].length&&(delete a.A[c],a.B--));return d};
g.Fe=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Jg&&f.listener==b&&f.eh==!!c&&f.sd==d)return e}return-1};
g.Ie=function(a,b,c,d,e){if(g.ia(b)){for(var f=0;f<b.length;f++)g.Ie(a,b[f],c,d,e);return null}c=g.Je(c);return g.Ce(a)?a.S(b,c,d,e):g.Ke(a,b,c,!1,d,e)};
g.Ke=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=!!e,p=g.Le(a);p||(a[Me]=p=new g.Ee(a));c=g.Ge(p,b,c,d,e,f);if(c.A)return c;d=Maa();c.A=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,k);else if(a.attachEvent)a.attachEvent(Ne(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");Oe++;return c};
Maa=function(){var a=Naa,b=Pe?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);
if(!c)return c};
return b};
g.Qe=function(a){if(g.ma(a)||!a||a.Jg)return!1;var b=a.src;if(g.Ce(b))return b.tv(a);var c=a.type,d=a.A;b.removeEventListener?b.removeEventListener(c,d,a.eh):b.detachEvent&&b.detachEvent(Ne(c),d);Oe--;(c=g.Le(b))?(g.He(c,a),0==c.B&&(c.src=null,b[Me]=null)):De(a);return!0};
Ne=function(a){return a in Re?Re[a]:Re[a]="on"+a};
Te=function(a,b,c,d){var e=!0;if(a=g.Le(a))if(b=a.A[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.eh==c&&!f.Jg&&(f=Se(f,d),e=e&&!1!==f)}return e};
Se=function(a,b){var c=a.listener,d=a.sd||a.src;a.Di&&g.Qe(a);return c.call(d,b)};
Naa=function(a,b){if(a.Jg)return!0;if(!Pe){var c=b||g.m("window.event"),d=new g.Ae(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(r){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.currentTarget;f;f=f.parentNode)c.push(f);for(var f=a.type,k=c.length-1;!d.Wf&&0<=k;k--){d.currentTarget=c[k];var p=Te(c[k],f,!0,d),e=e&&p}for(k=0;!d.Wf&&k<c.length;k++)d.currentTarget=c[k],p=Te(c[k],f,!1,d),e=e&&p}return e}return Se(a,new g.Ae(b,
this))};
g.Le=function(a){a=a[Me];return a instanceof g.Ee?a:null};
g.Je=function(a){if(g.na(a))return a;a[Ue]||(a[Ue]=function(b){return a.handleEvent(b)});
return a[Ue]};
g.We=function(){return g.Jc?"Webkit":g.Gc?"Moz":g.Ic?"ms":g.Ve?"O":null};
g.Xe=function(){return g.Jc?"-webkit":g.Gc?"-moz":g.Ic?"-ms":g.Ve?"-o":null};
g.Ye=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.Ze=function(a,b){return a&&b?b instanceof g.Ye?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.af=function(a,b){var c=$e[b];if(!c){var d=g.Ea(b),c=d;void 0===a.style[d]&&(d=g.We()+g.Fa(d),void 0!==a.style[d]&&(c=d));$e[b]=c}return c};
g.bf=function(a,b){var c=a.style[g.Ea(b)];return"undefined"!==typeof c?c:a.style[g.af(a,b)]||""};
g.cf=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.df=function(a,b){a.style.height=g.cf(b,!0)};
g.ef=function(a,b){a.style.width=g.cf(b,!0)};
g.ff=function(a,b){a.style.display=b?"":"none"};
g.hf=function(){var a=g.se("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(g.gf[d]=c.toString())}};
jf=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
kf=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};
g.lf=function(a){a=void 0!==g.gf[a]?g.gf[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};
g.mf=function(a,b){return!!((g.lf("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
g.nf=function(a,b){(a=g.x(a))&&a.style&&(g.ff(a,b),g.Xd(a,"hid",!b))};
g.of=function(a){return(a=g.x(a))?!("none"==a.style.display||g.z(a,"hid")):!1};
Oaa=function(a){if(a=g.x(a))g.of(a)?(g.ff(a,!1),g.A(a,"hid")):(g.ff(a,!0),g.D(a,"hid"))};
g.F=function(a){(0,g.u)(arguments,function(a){!g.ka(a)||a instanceof window.Element?g.nf(a,!0):(0,g.u)(a,function(a){g.F(a)})})};
g.G=function(a){(0,g.u)(arguments,function(a){!g.ka(a)||a instanceof window.Element?g.nf(a,!1):(0,g.u)(a,function(a){g.G(a)})})};
g.pf=function(a){(0,g.u)(arguments,function(a){g.ka(a)?(0,g.u)(a,function(a){g.pf(a)}):Oaa(a)})};
g.rf=function(){this.A=this.minor=this.major=0;this.B="";var a=g.m("window.navigator.plugins"),b=g.m("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.B=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,p,r,B;if(g.qf)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(C){k=null}else r=window.document.body,B=window.document.createElement("object"),B.setAttribute("type","application/x-shockwave-flash"),k=r.appendChild(B);if(k&&"GetVariable"in k)try{p=k.GetVariable("$version")}catch(C){p=""}r&&B&&r.removeChild(B);(k=p||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
sf=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
tf=function(a){return-1<a.B.indexOf("Gnash")&&-1==a.B.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
Paa=function(a){return g.uf?!sf(a,11,2):g.vf?!sf(a,11,3):!tf(a)};
wf=function(a,b,c){if(b){a=g.la(a)?g.Qc(a):a;var d=g.Wa(c.attrs);d.tabindex=0;var e=g.Wa(c.params);e.flashvars=g.qd(c.args);if(g.qf){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.zf=function(a,b){a=g.la(a)?g.Qc(a):a;b=g.he(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=g.rf.getInstance();sf(c,b.minVersion)?(c=xf(b,c),wf(a,c,b)):yf(a,b,c)};
Af=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=g.he(a);var d=!!b,e=g.x(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var k=null;if(window.document.referrer){var p=window.document.referrer.substring(0,128);Faa(p)||(k=p)}else k="unknown";k&&(d=!0,a.args.framer=k)}k=g.rf.getInstance();if(sf(k,a.minVersion)){var p=xf(a,k),r="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(r=e.getAttribute("src")||e.movie);(r!=p||d)&&wf(f,p,a);Paa(k)&&Qaa()}else yf(f,a,k);c&&c()}else g.zb(function(){Af(a,
b,c)},50)}};
yf=function(a,b,c){0==c.major&&b.fallback?b.fallback():0==c.major&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+g.Gb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};
xf=function(a,b){var c;(c=tf(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!sf(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
Qaa=function(){var a=g.x("flash10-promo-div"),b=g.mf(g.hf.getInstance(),107);a&&!b&&g.F(a)};
g.Bf=function(a,b){var c=a.match(Raa);window.spf.style.load(a,c?c[1]:"",b)};
Ff=function(a,b){g.qb.call(this);this.X=this.P=a;this.Y=b;this.F=!1;this.B={};this.eb=this.ia=null;this.ga=new g.ub;g.tb(this,this.ga);this.D={};this.G=this.gb=this.C=this.xb=this.A=null;this.ka=!1;this.J=this.H=this.O=this.T=null;this.lb={};this.Qc=["onReady"];this.qb=[];this.Ib=null;this.Ub=0;this.qa={};Cf(this);this.le("onDetailedError",(0,g.n)(this.iH,this));this.le("onTabOrderChange",(0,g.n)(this.Bx,this));this.le("onTabAnnounce",(0,g.n)(this.Go,this));this.le("WATCH_LATER_VIDEO_ADDED",(0,g.n)(this.mH,
this));this.le("WATCH_LATER_VIDEO_REMOVED",(0,g.n)(this.nH,this));this.le("onMouseWheelCapture",(0,g.n)(this.RG,this));this.le("onMouseWheelRelease",(0,g.n)(this.SG,this));this.le("onAdAnnounce",(0,g.n)(this.Go,this));this.ab=!1;this.mc=g.Df||g.Ef;this.Ta=this.aa=null;g.Ie(this.P,"mousewheel",this.kt,!1,this);g.Ie(this.P,"wheel",this.kt,!1,this)};
Hf=function(a,b){a.xb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.Y,a.A.attrs.id=a.Y);a.X.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.Y;a.gb||(a.gb=Gf(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.ef(a.X,Number(c)||c);(c=a.A.attrs.height)&&g.df(a.X,Number(c)||c)};
If=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.B.loadVideoByPlayerVars(a.A.args):a.B.cueVideoByPlayerVars(a.A.args))};
Jf=function(a){if(!g.ca(a.A.disable.flash)){var b=a.A.disable,c;c=sf(g.rf.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
Mf=function(a){var b;if(!(b=!a.A.html5&&Jf(a))){if(!g.ca(a.A.disable.html5)){var c;b=!0;void 0!=a.A.args.deviceHasDisplay&&(b=a.A.args.deviceHasDisplay);if(2.2==Kf)c=!0;else{a:{var d=b;b=g.m("yt.player.utils.videoElement_");b||(b=window.document.createElement("video"),g.l("yt.player.utils.videoElement_",b,void 0));try{if(b.canPlayType)for(var d=d?Saa:Taa,e=0;e<d.length;e++)if(b.canPlayType(d[e])){c=null;break a}c="fmt.noneavailable"}catch(f){c="html5.missingapi"}}c=!c}c&&(c=Lf(a)||a.A.assets.js);
a.A.disable.html5=!c;c||(a.A.args.html5_unavailable="1")}b=!!a.A.disable.html5}return b?Jf(a)?"flash":"unsupported":"html5"};
Pf=function(a,b){if(!b||(5!=(Uaa[b.errorCode]||5)?0:-1!=Vaa.indexOf(b.errorCode))){var c=Nf(a);c&&c.stopVideo&&c.stopVideo();if(Jf(a)){var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.he(c));d.args.autoplay=1;d.args.html5_unavailable="1";Hf(a,d);Of(a,"flash")}}};
Of=function(a,b){a.isDisposed()||(b||(b=Mf(a)),("flash"==b?a.xM:"html5"==b?a.yM:a.zM).call(a))};
Lf=function(a){var b=!0,c=Nf(a);c&&a.A&&(a=a.A,b=g.w(c,"version")==a.assets.js);return b&&!!g.m("yt.player.Application.create")};
Nf=function(a){var b=g.x(a.C);!b&&a.X&&a.X.querySelector&&(b=a.X.querySelector("#"+a.C));return b};
Qf=function(a,b,c){var d=b[c];return function(){try{return a.Ib=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.Ib=e,g.Db(e,"WARNING"))}}};
Cf=function(a){a.F=!1;if(a.eb)for(var b in a.D)a.eb(b,a.D[b]);for(var c in a.qa)g.Bb((0,window.parseInt)(c,10));a.qa={};a.ia=null;a.eb=null;for(var d in a.B)a.B[d]=null;a.B.addEventListener=(0,g.n)(a.le,a);a.B.removeEventListener=(0,g.n)(a.RK,a);a.B.destroy=(0,g.n)(a.dispose,a);a.B.getLastError=(0,g.n)(a.Ky,a);a.B.getPlayerType=(0,g.n)(a.Zy,a);a.B.getCurrentVideoConfig=(0,g.n)(a.py,a);a.B.loadNewVideoConfig=(0,g.n)(a.ao,a);a.B.isReady=(0,g.n)(a.MM,a)};
Gf=function(a,b){var c=b;if("string"==typeof b){if(a.lb[b])return a.lb[b];c=function(){var a=g.m(b);a&&a.apply(g.da,arguments)};
a.lb[b]=c}return c?c:null};
Waa=function(a,b){var c="ytPlayer"+b+a.Y;a.D[b]=c;g.da[c]=function(c){var e=g.zb(function(){a.isDisposed()||(a.ga.na(b,c),g.Ua(a.qa,String(e)))},0);
g.Va(a.qa,String(e),!0)};
return c};
Rf=function(a){return(a=Nf(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
Sf=function(a){g.Ed("dcp");a.cancel();Cf(a);a.G=null;a.A&&(a.A.loaded=!1);var b=Nf(a);"html5"==Rf(a)?a.O=b:b&&b.destroy&&b.destroy();g.ad(a.P);g.ce(a.qb);a.qb.length=0;a.H=null;a.J=null};
g.Vf=function(a,b){a=g.la(a)?g.Qc(a):a;b=g.he(b);var c=g.Tf+"_"+g.qa(a),d=g.Uf[c];if(d)return d.ao(b),d.B;d=new Ff(a,c);g.Uf[c]=d;g.v("player-added",d.B);g.rb(d,g.ra(Xaa,d));g.zb(function(){d.ao(b)},0);
return d.B};
Xaa=function(a){g.Uf[a.getId()]=null};
g.Wf=function(a){a=g.x(a);if(!a)return null;var b=g.Tf+"_"+g.qa(a),c=g.Uf[b];c||(c=new Ff(a,b),g.Uf[b]=c);return c.B};
g.Xf=function(){return g.z(g.x("page-container"),"remote-connected")};
Yaa=function(){g.l("yt.abuse.botguardInitialized",je,void 0);g.l("yt.abuse.invokeBotguard",g.ke,void 0);g.l("yt.abuse.dclkstatus.checkDclkStatus",le,void 0);g.l("yt.player.exports.navigate",g.ye,void 0);g.l("yt.player.embed",g.Vf,void 0);g.l("yt.player.getPlayerByElement",g.Wf,void 0);g.l("yt.util.activity.init",g.ee,void 0);g.l("yt.util.activity.getTimeSinceActive",g.fe,void 0);g.l("yt.util.activity.setTimestamp",de,void 0);var a=g.m("ytplayer.config");Yf(a);g.m("ytspf.enabled")&&(Zf=g.Ab($f,5E3),
(a=g.ag())?(a.addEventListener("onReady",$f),a.addEventListener("onStateChange",$f)):bg("unable to init PP monitor"))};
Yf=function(a){for(var b in g.Uf){var c=g.Uf[b];c&&c.cancel()}if(a=a||null){b=g.ag();var d=!0,c=g.cg;g.cg=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(dg="",g.Vf("player-api",a)):b.playVideo();a=g.he(a);a.loaded=!0}$f();g.l("ytplayer.config",a,void 0)};
g.ag=function(){var a=g.m("yt.player.getPlayerByElement");return a?a("player-api"):null};
$f=function(){var a=g.ag();if(a){var b;b=g.x("player");b=!b||g.z(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.t("PAGE_NAME"),e=g.Xf();!c||d||e||(bg("PP playing off watch (paused)"),a.pauseVideo());b&&d?bg("PP off-screen on watch"):b||d||bg("PP !off-screen off watch")}};
bg=function(a){var b=g.t("PAGE_NAME");b&&(b=[b,dg,g.m("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.l("yt.www.persistentplayer.issue",a,void 0),g.Db(Error(a),"WARNING"))};
fg=function(){g.Ed("ol");g.t("CSI_TICK_PAINT_TIME")?window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.Ed("cpt");eg()},0)}):window.document.hidden?(g.Ed("cpt"),eg()):(0,window.setTimeout)(function(){g.Ed("cpt");
eg()},0):eg()};
eg=function(){gg("init");var a=g.t("PAGE_NAME",void 0);a&&gg("init-"+a)};
gg=function(a){g.Pb()?hg.push(g.Qb(g.ra(g.Ob,a),0)):g.v(a)};
ig=function(){g.Tb(hg);hg.length=0;var a=g.t("PAGE_NAME",void 0);a&&g.Ob("dispose-"+a);g.Ob("dispose")};
Zaa=function(){fg()};
$aa=function(){g.t("TIMING_REPORT_ON_UNLOAD")&&Dd(!0);g.t("CSI_MORE")&&Rd("u");Pd("u");ig();g.Ob("pageunload")};
aba=function(a,b,c,d,e){for(var f=window.document.getElementsByTagName("script"),k=!1,p=0,r=f.length;p<r;p++)if(0<f[p].src.indexOf("/debug-")){k=!0;break}k&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.Db(e))};
ng=function(){jg=1;kg=lg=0;g.t("TIMING_REPORT_ON_UNLOAD")&&Dd(!0);g.t("CSI_MORE")&&Rd("n");Pd("n");Id();Gd("n");Cd("mark_navigation_requested");mg(bba);g.Ob("navigate")};
rg=function(a){a=a.detail.part||a.detail.partial;g.Ed("nc"+lg);++lg;if(!a.data||!a.data.deferDispose){var b=1==jg;jg=2;b?(mg(cba),og()):mg(dba);if(b=a.data&&a.data.swfcfg)pg(a.timing,b.args),qg(b)}};
sg=function(){g.Ed("np"+kg);++kg};
tg=function(a){a=a.detail.response;var b=1==jg;jg=3;b&&(mg(eba),og());if(b=a.data&&a.data.swfcfg)pg(a.timing,b.args),qg(b)};
wg=function(a){g.Ed("nd");a=a.detail.response;g.ug=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;Fd(void 0).yt_nav=b;Gd("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);Fd(void 0).srt=b;var c=(b=!!a.spfCached)?"hot":"warm";Fd(void 0).yt_lt=c;var c=!!a.spfPrefetched,d=+c;Fd(void 0).yt_pft=d;d=a.responseStart-a.fetchStart;Kd(void 0).span.preq=d;"redirectStart"in a&&Ld(a);mg(vg);window.document.getElementById("content").style.height="";g.t("EXP_LACT_HISTORY")&&
b&&!c&&de();fg();jg=0};
xg=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.Db(a)};
yg=function(a){g.Ud(g.qd({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
gba=function(){fba()};
hba=function(){};
og=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");ig();var a=g.t("TIMING_ACTION"),b;for(b in g.wb)delete g.wb[b];g.xb("PREVIOUS_ACTION",a);g.l("ytplayer.config",null,void 0);if((b=g.ag())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())dg=b,(b=g.x("movie_player"))&&b.stopVideo?(b.stopVideo(),dg="recovered"):dg="missing2"}else dg="missing";$f()};
qg=function(a){"cfg"in Ad(void 0)||g.Ed("cfg");Yf(a)};
mg=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Sb(zg);zg=g.Rb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var f=b.style;f.transitionDuration=f.webkitTransitionDuration=c+"ms";f.width=d+"%";g.Bb(Ag);Ag=g.zb(function(){b.className=e},c)},0)};
fba=function(){var a=vg[0]+50;g.Bb(Ag);Ag=g.zb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
pg=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.u)(iba,function(a){a in b&&(delete b[a],e.push(a))});
g.t("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.Ud(g.qd(c)))};
Bg=function(){g.Ub.call(this,"www/base");this.C=0};
Cg=function(a){(a=a.detail.name)&&Xb(a)};
g.aa=[];g.Dg=g.Dg||{};g.da=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.Bd=Date.now||function(){return+new Date};sa[" "]=g.fa;var eaa,faa,gaa,haa,iaa,jaa,daa;g.Aa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.Eg=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.jba=2147483648*Math.random()|0;g.Ka=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.la(a))return g.la(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.kba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.la(a))return g.la(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
g.Wd=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,k=g.la(a)?a.split(""):a,p=0;p<d;p++)if(p in k){var r=k[p];
b.call(c,r,p,a)&&(e[f++]=r)}return e};
g.Fg=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=g.la(a)?a.split(""):a,k=0;k<d;k++)k in f&&(e[k]=b.call(c,f[k],k,a));
return e};
g.Gg=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.n)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.u)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.Hg=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;
return!1};
g.Ig=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;
return!0};g.Jg=g.Pa(!1);g.Kg=g.Pa(!0);g.Lg=g.Pa(null);var Xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var Mg=g.da.navigator;if(Mg){var Ng=Mg.userAgent;if(Ng){g.Za=Ng;break a}}g.Za=""};var pb;g.eb.prototype.get=function(){var a;0<this.B?(this.B--,a=this.A,this.A=a.next,a.next=null):a=this.C();return a};
g.eb.prototype.put=function(a){this.D(a);this.B<this.G&&(this.B++,a.next=this.A,this.A=a)};var lb=new g.eb(function(){return new gb},function(a){a.reset()},100);
fb.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.B=null),a.next=null);return a};
gb.prototype.set=function(a,b){this.se=a;this.scope=b;this.next=null};
gb.prototype.reset=function(){this.next=this.scope=this.se=null};var ib,jb=!1,kb=new fb;g.qb.prototype.Tc=!1;g.qb.prototype.isDisposed=function(){return this.Tc};
g.qb.prototype.dispose=function(){this.Tc||(this.Tc=!0,this.W())};
g.qb.prototype.W=function(){if(this.Gb)for(;this.Gb.length;)this.Gb.shift()()};g.q(g.ub,g.qb);g.h=g.ub.prototype;g.h.subscribe=function(a,b,c){var d=this.xd[a];d||(d=this.xd[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.h.unsubscribe=function(a,b,c){if(a=this.xd[a]){var d=this.A;if(a=g.Ja(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.yd(a)}return!1};
g.h.yd=function(a){var b=this.A[a];if(b){var c=this.xd[b];0!=this.C?(this.B.push(a),this.A[a+1]=g.fa):(c&&g.Na(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.h.na=function(a,b){var c=this.xd[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.G)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.C++;try{for(e=0,f=c.length;e<f;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.C--,0<this.B.length&&0==this.C)for(;c=this.B.pop();)this.yd(c)}}return 0!=e}return!1};
g.h.clear=function(a){if(a){var b=this.xd[a];b&&((0,g.u)(b,this.yd,this),delete this.xd[a])}else this.A.length=0,this.xd={}};
g.h.rb=g.ba(1);g.h.W=function(){g.ub.N.W.call(this);this.clear();this.B.length=0};g.wb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.l("yt.config_",g.wb,void 0);g.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Eb=window.yt&&window.yt.msgs_||g.m("window.ytcfg.msgs")||{};g.l("yt.msgs_",g.Eb,void 0);g.qf="Microsoft Internet Explorer"==window.navigator.appName;var lba=g.m("yt.pubsub.instance_")||new g.ub;g.ub.prototype.subscribe=g.ub.prototype.subscribe;g.ub.prototype.unsubscribeByKey=g.ub.prototype.yd;g.ub.prototype.publish=g.ub.prototype.na;g.ub.prototype.clear=g.ub.prototype.clear;g.l("yt.pubsub.instance_",lba,void 0);var Jb=g.m("yt.pubsub.subscribedKeys_")||{};g.l("yt.pubsub.subscribedKeys_",Jb,void 0);var Lb=g.m("yt.pubsub.topicToKeys_")||{};g.l("yt.pubsub.topicToKeys_",Lb,void 0);var Kb=g.m("yt.pubsub.isSynchronous_")||{};
g.l("yt.pubsub.isSynchronous_",Kb,void 0);var Ib=g.m("yt.pubsub.skipSubId_")||null;g.l("yt.pubsub.skipSubId_",Ib,void 0);g.h=g.Ub.prototype;g.h.bL=function(){this.Hj()||this.init()};
g.h.enable=function(){this.A=1;(0,g.u)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.bL,this),this.subscribe("dispose-"+a,this.dispose,this),g.t("PAGE_NAME")==a&&g.Vb(this))},this)};
g.h.init=function(){g.Sb(this.B);this.A=2;this.H&&this.H()};
g.h.Hj=function(){return 2==this.A};
g.h.dispose=function(){this.A=3;g.Sb(this.B);this.G&&this.G()};
g.h.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.Db(a)}};
g.h.subscribe=function(a,b,c){a=g.Mb(a,b,c);this.D.push(a);return a};
g.h.clear=function(){g.Nb(this.D);this.D=[]};var Wb=g.m("yt.modules.registry_")||{};g.l("yt.modules.registry_",Wb,void 0);var saa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};g.mba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.nba=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");g.$b.prototype.Lf=!0;g.$b.prototype.ue=function(){return this.A};
g.$b.prototype.toString=function(){return"Const{"+this.A+"}"};
var Zb={};g.cc.prototype.Lf=!0;var bc={};g.cc.prototype.ue=function(){return this.A};
var qaa=g.ec(""),paa=/^([-,."'%_!# a-zA-Z0-9]+|(?:rgb|hsl)a?\([0-9.%, ]+\))$/;g.gc.prototype.Lf=!0;g.gc.prototype.ue=function(){return this.A};
g.gc.prototype.lm=!0;g.gc.prototype.qg=function(){return 1};
var naa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,fc={};g.ic("about:blank");g.lc.prototype.Lf=!0;g.lc.prototype.ue=function(){return this.A};
g.lc.prototype.lm=!0;g.lc.prototype.qg=function(){return 1};
var kc={};var sc,raa,oaa,nc;g.oc.prototype.lm=!0;g.oc.prototype.qg=function(){return this.B};
g.oc.prototype.Lf=!0;g.oc.prototype.ue=function(){return this.A};
sc=/^[a-zA-Z0-9-]+$/;raa={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};oaa={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};nc={};g.oba=g.qc("<!DOCTYPE html>",0);g.Og=g.qc("",0);g.Pg=g.qc("<br>",0);var Ac={};var taa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,uaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.pba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.h=g.Ec.prototype;g.h.clone=function(){return new g.Ec(this.x,this.y)};
g.h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.h.scale=function(a,b){var c=g.ma(b)?b:a;this.x*=a;this.y*=c;return this};var Rg,Lc,Sg;g.Ve=bb();g.Ic=g.$a("Trident")||g.$a("MSIE");g.Hc=g.$a("Edge");g.Qg=g.Hc||g.Ic;g.Gc=g.$a("Gecko")&&!(g.ya(g.Za.toLowerCase(),"webkit")&&!g.$a("Edge"))&&!(g.$a("Trident")||g.$a("MSIE"))&&!g.$a("Edge");g.Jc=g.ya(g.Za.toLowerCase(),"webkit")&&!g.$a("Edge");g.Jc&&g.$a("Mobile");g.vf=g.$a("Macintosh");g.uf=g.$a("Windows");g.qba=g.$a("Linux")||g.$a("CrOS");Rg=g.da.navigator||null;Rg&&g.ya(Rg.appVersion||"","X11");g.rba=g.$a("Android");g.sba=g.Fc();g.tba=g.$a("iPad");
g.Mc=function(){if(g.Ve&&g.da.opera){var a;var b=g.da.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=vaa())&&(a=b?b[1]:"");return g.Ic&&(b=Kc(),b>(0,window.parseFloat)(a))?String(b):a}();
Lc={};Sg=g.da.document;g.Oc=Sg&&g.Ic?Kc()||("CSS1Compat"==Sg.compatMode?(0,window.parseInt)(g.Mc,10):5):void 0;var waa;waa=!g.Ic||g.Pc(9);g.uba=!g.Gc&&!g.Ic||g.Ic&&g.Pc(9)||g.Gc&&g.Nc("1.9.1");g.Tg=g.Ic&&!g.Nc("9");g.vba=g.Ic||g.Ve||g.Jc;g.wba=g.Ic&&!g.Pc(9);var Sc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};g.Ug="StopIteration"in g.da?g.da.StopIteration:{message:"StopIteration",stack:""};g.id=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;var ud={},Baa=0,xba=g.m("yt.net.ping.workerUrl_")||null;g.l("yt.net.ping.workerUrl_",xba,void 0);g.vd.prototype.Yb=g.ba(2);g.wd.prototype.toString=function(){return this.topic};var yba=g.m("yt.pubsub2.instance_")||new g.ub;g.ub.prototype.subscribe=g.ub.prototype.subscribe;g.ub.prototype.unsubscribeByKey=g.ub.prototype.yd;g.ub.prototype.publish=g.ub.prototype.na;g.ub.prototype.clear=g.ub.prototype.clear;g.l("yt.pubsub2.instance_",yba,void 0);g.Vg=g.m("yt.pubsub2.subscribedKeys_")||{};g.l("yt.pubsub2.subscribedKeys_",g.Vg,void 0);g.Wg=g.m("yt.pubsub2.topicToKeys_")||{};g.l("yt.pubsub2.topicToKeys_",g.Wg,void 0);g.Xg=g.m("yt.pubsub2.isAsync_")||{};
g.l("yt.pubsub2.isAsync_",g.Xg,void 0);g.l("yt.pubsub2.skipSubKey_",null,void 0);g.q(zd,g.vd);var Eaa=new g.wd("timing-sent",zd);var Md=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},Caa=(0,g.n)(Md.clearResourceTimings||Md.webkitClearResourceTimings||Md.mozClearResourceTimings||Md.msClearResourceTimings||Md.oClearResourceTimings||g.fa,Md),Cd=Md.mark?function(a){Md.mark(a)}:g.fa;g.zba=g.Jc?"webkit":g.Gc?"moz":g.Ic?"ms":g.Ve?"o":"";g.Yg=g.m("yt.dom.getNextId_");if(!g.Yg){g.Yg=function(){return++Aba};
g.l("yt.dom.getNextId_",g.Yg,void 0);var Aba=0};g.Zd.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.Zd.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.Zd.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Gaa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.$d=g.m("yt.events.listeners_")||{};g.l("yt.events.listeners_",g.$d,void 0);var be=g.m("yt.events.counter_")||{count:0};g.l("yt.events.counter_",be,void 0);var Haa={enablejsapi:1},Iaa={},Jaa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};ge.prototype.clone=function(){var a=new ge,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ha(c)?a[b]=g.Wa(c):a[b]=c}return a};g.ie=null;g.oe=/\s*;\s*/;g.h=g.ne.prototype;g.h.isEnabled=function(){return window.navigator.cookieEnabled};
g.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.Bd)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+f};
g.h.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.oe),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};
g.h.remove=function(a,b,c){var d=g.ca(this.get(a));this.set(a,"",0,b,c);return d};
g.h.Rb=g.ba(3);g.h.tb=g.ba(4);g.h.isEmpty=function(){return!this.A.cookie};
g.h.rb=g.ba(0);g.h.re=g.ba(5);g.h.clear=function(){for(var a=g.pe(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.qe=new g.ne(window.document);g.qe.B=3950;var Pe,Cba;g.Bba=!g.Ic||g.Pc(9);Pe=!g.Ic||g.Pc(9);Cba=g.Ic&&!g.Nc("9");!g.Jc||g.Nc("528");g.Gc&&g.Nc("1.9b")||g.Ic&&g.Nc("8")||g.Ve&&g.Nc("9.5")||g.Jc&&g.Nc("528");g.Gc&&!g.Nc("8")||g.Ic&&g.Nc("9");g.ze.prototype.stopPropagation=function(){this.Wf=!0};
g.ze.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Fu=!1};g.Zg=g.Ic?"focusin":"DOMFocusIn";g.Dba=g.Ic?"focusout":"DOMFocusOut";g.$g=g.Jc?"webkitTransitionEnd":g.Ve?"otransitionend":"transitionend";g.q(g.Ae,g.ze);
g.Ae.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;e?g.Gc&&(g.ua(e,"nodeName")||(e=null)):"mouseover"==c?e=a.fromElement:"mouseout"==c&&(e=a.toElement);this.relatedTarget=e;null===d?(this.offsetX=g.Jc||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=g.Jc||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?
a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Xm=g.vf?a.metaKey:a.ctrlKey;this.state=a.state;this.Cb=a;a.defaultPrevented&&this.preventDefault()};
g.Ae.prototype.stopPropagation=function(){g.Ae.N.stopPropagation.call(this);this.Cb.stopPropagation?this.Cb.stopPropagation():this.Cb.cancelBubble=!0};
g.Ae.prototype.preventDefault=function(){g.Ae.N.preventDefault.call(this);var a=this.Cb;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Cba)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
g.Ae.prototype.fq=g.ba(6);var Kaa;g.Be="closure_listenable_"+(1E6*Math.random()|0);Kaa=0;g.Ee.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.A))return!1;var e=this.A[a];b=g.Fe(e,b,c,d);return-1<b?(De(e[b]),g.Ma(e,b),0==e.length&&(delete this.A[a],this.B--),!0):!1};
g.Ee.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.A)if(!a||c==a){for(var d=this.A[c],e=0;e<d.length;e++)++b,De(d[e]);delete this.A[c];this.B--}return b};var Me="closure_lm_"+(1E6*Math.random()|0),Re={},Oe=0,Ue="__closure_events_fn_"+(1E9*Math.random()>>>0);g.h=g.Ye.prototype;g.h.getHeight=function(){return this.bottom-this.top};
g.h.clone=function(){return new g.Ye(this.top,this.right,this.bottom,this.left)};
g.h.contains=function(a){return g.Ze(this,a)};
g.h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.h.scale=function(a,b){var c=g.ma(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var $e;$e={};g.ah=g.Gc?"MozUserSelect":g.Jc||g.Hc?"WebkitUserSelect":null;g.Ef=g.$a("Firefox");g.bh=g.Fc()||g.$a("iPod");g.ch=g.$a("iPad");g.Eba=g.$a("Android")&&!(cb()||g.$a("Firefox")||bb()||g.$a("Silk"));g.Df=cb();g.dh=g.$a("Safari")&&!(cb()||g.$a("Coast")||bb()||g.$a("Edge")||g.$a("Silk")||g.$a("Android"))&&!(g.Fc()||g.$a("iPad")||g.$a("iPod"));g.ga(g.hf);g.gf=g.m("yt.prefs.UserPrefs.prefs_")||{};g.l("yt.prefs.UserPrefs.prefs_",g.gf,void 0);g.h=g.hf.prototype;g.h.get=function(a,b){kf(a);jf(a);var c=void 0!==g.gf[a]?g.gf[a].toString():null;return null!=c?c:b?b:""};
g.h.set=function(a,b){kf(a);jf(a);if(null==b)throw"ExpectedNotNull";g.gf[a]=b.toString()};
g.h.remove=function(a){kf(a);jf(a);delete g.gf[a]};
g.h.save=function(){var a;a=[];for(var b in g.gf)a.push(b+"="+(0,window.escape)(g.gf[b]));a=a.join("&");g.re("PREF",a,63072E3)};
g.h.clear=function(){g.gf={}};g.eh=g.Qa(function(){if(g.Ic)return g.Nc("10.0");var a=window.document.createElement("DIV"),b=g.Xe(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");g.wc(a,g.uc("div",{style:c}));return""!=g.bf(a.firstChild,"transition")});g.ga(g.rf);g.rf.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Raa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Kf;var fh=g.Za,fh=fh.toLowerCase();if(g.ya(fh,"android")){var gh=fh.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(gh)Kf=Number(gh[1]);else{var hh={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},ih=fh.match("("+g.Sa(hh).join("|")+")");Kf=ih?hh[ih[0]]:0}}else Kf=void 0;var Saa=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],Taa=['audio/mp4; codecs="mp4a.40.2"'];var Uaa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"drm.unavailable":5};g.q(Ff,g.qb);var Vaa=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.h=Ff.prototype;g.h.getId=function(){return this.Y};
g.h.ao=function(a,b){this.isDisposed()||(Hf(this,a),b||Mf(this),Of(this,b),this.F&&If(this))};
g.h.py=function(){return this.xb};
g.h.yM=function(){if(!this.ka){var a=Lf(this);a&&"html5"==Rf(this)?(this.G="html5",this.F||this.Ig()):(Sf(this),this.G="html5",a&&this.O?(this.P.appendChild(this.O),this.Ig()):(this.A.loaded=!0,this.T=(0,g.n)(function(){var a=this.P,c=this.A.clone();g.m("yt.player.Application.create")(a,c);this.Ig()},this),this.ka=!0,a?this.T():(g.Cc(this.A.assets.js,this.T),g.Bf(this.A.assets.css))))}};
g.h.xM=function(){var a=this.A.clone();if(!this.H){var b=Nf(this);b&&(this.H=window.document.createElement("span"),this.H.tabIndex=0,this.qb.push(g.E(this.H,"focus",(0,g.n)(this.Us,this))),this.J=window.document.createElement("span"),this.J.tabIndex=0,this.qb.push(g.E(this.J,"focus",(0,g.n)(this.Us,this))),g.bd(this.H,b),g.cd(this.J,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Rf(this)?(this.G="flash",this.F||Af(a,!1,(0,g.n)(this.Ig,this))):(Sf(this),this.G=
"flash",this.A.loaded=!0,g.zf(this.P,a),this.Ig())};
g.h.Us=function(){Nf(this).focus()};
g.h.Ig=function(){if(!this.isDisposed()){var a=Nf(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(f){}if(b)if(this.ka=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))Pf(this);else{Cf(this);this.F=!0;a=Nf(this);a.addEventListener&&(this.ia=Qf(this,a,"addEventListener"));a.removeEventListener&&(this.eb=Qf(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.B[d]||(this.B[d]=Qf(this,a,
d))}for(var e in this.D)this.ia(e,this.D[e]);If(this);this.gb&&this.gb(this.B);this.ga.na("onReady",this.B)}else this.Ub=g.zb((0,g.n)(this.Ig,this),50)}};
g.h.MM=function(){return this.F};
g.h.le=function(a,b){if(!this.isDisposed()){var c=Gf(this,b);if(c){if(!g.La(this.Qc,a)&&!this.D[a]){var d=Waa(this,a);this.ia&&this.ia(a,d)}this.ga.subscribe(a,c);"onReady"==a&&this.F&&g.zb(g.ra(c,this.B),0)}}};
g.h.RK=function(a,b){if(!this.isDisposed()){var c=Gf(this,b);c&&this.ga.unsubscribe(a,c)}};
g.h.Bx=function(a){a=a?zaa:yaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.H||b==this.J||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.h.Go=function(a){g.v("a11y-announce",a)};
g.h.iH=function(a){Pf(this,a)};
g.h.mH=function(a){g.v("WATCH_LATER_VIDEO_ADDED",a)};
g.h.nH=function(a){g.v("WATCH_LATER_VIDEO_REMOVED",a)};
g.h.RG=function(){this.mc&&(this.ab||(this.Ta=g.Vc(window.document)),this.aa||(this.aa=g.Ie(window,"scroll",this.fJ,!1,this)));this.ab=!0};
g.h.SG=function(){this.aa&&(g.Qe(this.aa),this.aa=null);this.ab=!1};
g.h.kt=function(a){this.ab&&!this.mc&&a.preventDefault()};
g.h.fJ=function(){this.Ta&&window.scrollTo(this.Ta.x,this.Ta.y)};
g.h.zM=function(){Sf(this);this.G="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.A.messages.player_fallback||a;a=g.x("player-unavailable");g.x("unavailable-submessage")&&a&&(g.x("unavailable-submessage").innerHTML=b,(b=g.y("icon",a))&&g.zc(b,"icon")&&(b.src=g.w(b,"icon")),g.ff(a,!0),g.A(g.x("player"),"off-screen-trigger"))};
g.h.Zy=function(){return this.G||Rf(this)};
g.h.Ky=function(){return this.Ib};
g.h.cancel=function(){this.T&&g.Dc(this.A.assets.js,this.T);g.Bb(this.Ub);this.ka=!1};
g.h.W=function(){Sf(this);if(this.O&&this.A&&this.A.args.fflags&&-1!=this.A.args.fflags.indexOf("new_html5_dispose=true"))try{this.O.destroy()}catch(b){g.Db(b)}this.lb=null;for(var a in this.D)g.da[this.D[a]]=null;this.B=null;delete this.P;delete this.X;this.A&&(this.xb=this.A=this.A.fallback=null);Ff.N.W.call(this)};g.Uf={};g.Tf="player_uid_"+(1E9*Math.random()>>>0);var Fba=g.m("yt.abuse.botguardInitialized")||je;g.l("yt.abuse.botguardInitialized",Fba,void 0);var Gba=g.m("yt.abuse.invokeBotguard")||g.ke;g.l("yt.abuse.invokeBotguard",Gba,void 0);var Hba=g.m("yt.abuse.dclkstatus.checkDclkStatus")||le;g.l("yt.abuse.dclkstatus.checkDclkStatus",Hba,void 0);var Iba=g.m("yt.player.exports.navigate")||g.ye;g.l("yt.player.exports.navigate",Iba,void 0);var Jba=g.m("yt.player.embed")||g.Vf;g.l("yt.player.embed",Jba,void 0);var Kba=g.m("yt.player.getPlayerByElement")||g.Wf;
g.l("yt.player.getPlayerByElement",Kba,void 0);var Lba=g.m("yt.util.activity.init")||g.ee;g.l("yt.util.activity.init",Lba,void 0);var Mba=g.m("yt.util.activity.getTimeSinceActive")||g.fe;g.l("yt.util.activity.getTimeSinceActive",Mba,void 0);var Nba=g.m("yt.util.activity.setTimestamp")||de;g.l("yt.util.activity.setTimestamp",Nba,void 0);var Zf,dg;g.cg=null;dg="";var hg=[];var jg,Ag,zg,lg,kg,iba,bba,eba,cba,dba,vg;lg=0;kg=0;iba=["server_prefetched_vast","vmap"];bba=[900,60,"waiting"];eba=[500,99,"waiting"];cba=[300,60,"waiting"];dba=[400,99,"waiting"];vg=[300,101,"done"];window.yt=window.yt||{};g.l("yt.setConfig",g.xb,void 0);g.l("yt.getConfig",g.t,void 0);g.l("yt.hasMsg",g.Fb,void 0);g.l("yt.pubsub.publish",g.v,void 0);g.l("yt.pubsub.subscribe",g.Mb,void 0);g.l("yt.setMsg",function(a){vb(g.Eb,arguments)},void 0);
g.l("yt.setGoogMsg",function(a){vb(g.Eb,arguments)},void 0);
g.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=g.t("TIMING_INFO",{});"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);Od(c)},void 0);
g.l("ytcsi.tick",g.Ed,void 0);g.q(Bg,g.Ub);
Bg.prototype.enable=function(){window.onload=Zaa;window.onunload=$aa;window.onerror=aba;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",ng),window.addEventListener("spfpartprocess",rg),window.addEventListener("spfpartdone",sg),window.addEventListener("spfprocess",tg),window.addEventListener("spfdone",wg),window.addEventListener("spferror",xg),window.addEventListener("spfreload",yg),window.addEventListener("spfjsbeforeunload",Cg)),a.config=a.config||
{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",gba),this.subscribe("dispose",hba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
Bg.prototype.init=function(){Bg.N.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.t("PAGEFRAME_JS")?(b=g.t("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.m("ytbin.www.pageframe.setup")()}):a&&(a=g.m("yt.www.masthead.loadSearchbox"))&&a();
var a=g.t("JS_COMMON_MODULE"),d=g.t("JS_PAGE_MODULES");d||(d=[a]);a=g.t("JS_DELAY_LOAD",0);0<a?(g.Bb(this.C),this.C=g.zb(function(){b&&g.Cc(b,c);window.spf.script.require(d)},a)):(b&&g.Cc(b,c),window.spf.script.require(d));
Yaa();g.l("yt.timing.ready_",!0,void 0);Dd(!1);var a=!!g.m("yt.reactLoaded"),e=g.t("REACT_JS",void 0);!a&&e&&g.Cc(e,function(){g.l("yt.reactLoaded",!0,void 0)})};
Bg.prototype.dispose=function(){g.Bb(this.C);var a=g.m("ytbin.www.pageframe.cancelSetup");a&&a();g.Cb(Zf);if(a=g.ag())a.removeEventListener("onReady",$f),a.removeEventListener("onStateChange",$f);g.l("yt.timing.ready_",!1,void 0);Bg.N.dispose.call(this)};
Bg.prototype.disable=function(){Bg.N.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",ng),window.removeEventListener("spfpartprocess",rg),window.removeEventListener("spfpartdone",sg),window.removeEventListener("spfprocess",tg),window.removeEventListener("spfdone",wg),window.removeEventListener("spferror",xg),window.removeEventListener("spfreload",yg),window.removeEventListener("spfjsbeforeunload",Cg));window.onload=null;window.onunload=null;window.onerror=null};
g.Yb(new Bg);})(_yt_www);
