var _yt_www={};(function(g){var window=this;var baa,caa,Aa,Za,$a,kaa,eb,fb,laa,nb,maa,ub,Gb,Wb,vaa,Ic,yaa,zaa,xaa,nd,Aaa,xd,Ed,Gd,Hd,Jd,Ld,Daa,Od,Bd,Md,Nd,yd,Dd,Id,Fd,Pd,Faa,be,ee,he,je,re,se,Le,Me,Kaa,Ue,Ve,Laa,Ye,bf,$e,Ze,Maa,ef,ff,jf,lf,mf,nf,qf,tf,sf,pf,rf,uf,gf,kf,Saa,vf,wf,Taa,Uaa,Cf,Ef,Gf,Kf,Jf,Lf,Nf,Vaa,Waa,Xaa,Sf,Wf,Xf,Yf,ag,bg,cg,cba,dba,Tf,Vf,Rf,bba,Uf,fg,gg,pa,aaa;g.ba=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.ca=function(a){return void 0!==a};
g.l=function(a,b,c){a=a.split(".");c=c||g.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.m=function(a,b){for(var c=a.split("."),d=b||g.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.fa=function(){};
g.ga=function(a){a.getInstance=function(){return a.Bc?a.Bc:a.Bc=new a}};
g.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ia=function(a){return"array"==g.ha(a)};
g.ka=function(a){var b=g.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.la=function(a){return"string"==typeof a};
g.ma=function(a){return"number"==typeof a};
g.na=function(a){return"function"==g.ha(a)};
g.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.qa=function(a){return a[pa]||(a[pa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.p=function(a,b,c){g.p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.p.apply(null,arguments)};
g.ra=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.q=function(a,b){function c(){}
c.prototype=b.prototype;a.N=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,h){for(var k=Array(arguments.length-2),n=2;n<arguments.length;n++)k[n-2]=arguments[n];return b.prototype[c].apply(a,k)}};
g.sa=function(a){g.sa[" "](a);return a};
g.ta=function(a,b){return 0==a.lastIndexOf(b,0)};
g.va=function(a){return(0,window.encodeURIComponent)(String(a))};
g.wa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.xa=function(a,b){return-1!=a.indexOf(b)};
g.ya=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
g.Ba=function(a,b){for(var c=0,d=(0,g.za)(String(a)).split("."),e=(0,g.za)(String(b)).split("."),h=Math.max(d.length,e.length),k=0;0==c&&k<h;k++){var n=d[k]||"",r=e[k]||"",B=RegExp("(\\d*)(\\D*)","g"),C=RegExp("(\\d*)(\\D*)","g");do{var N=B.exec(n)||["","",""],V=C.exec(r)||["","",""];if(0==N[0].length&&0==V[0].length)break;c=Aa(0==N[1].length?0:(0,window.parseInt)(N[1],10),0==V[1].length?0:(0,window.parseInt)(V[1],10))||Aa(0==N[2].length,0==V[2].length)||Aa(N[2],V[2])}while(0==c)}return c};
Aa=function(a,b){return a<b?-1:a>b?1:0};
g.Ca=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
g.Da=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
g.Ea=function(a){var b=g.la(void 0)?g.ya(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
g.Ga=function(a,b,c){b=g.Fa(a,b,c);return 0>b?null:g.la(a)?a.charAt(b):a[b]};
g.Fa=function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return h;return-1};
g.Ia=function(a,b){return 0<=(0,g.Ha)(a,b)};
g.La=function(a,b){var c=(0,g.Ha)(a,b),d;(d=0<=c)&&g.Ka(a,c);return d};
g.Ka=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.Ma=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Na=function(a){return function(){return a}};
g.Oa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
g.Pa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Qa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Ra=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Sa=function(a,b){b in a&&delete a[b]};
g.Ta=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Ua=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.Wa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<Va.length;h++)c=Va[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.Ya=function(a){return g.xa(g.Xa,a)};
Za=function(){return g.Ya("Opera")||g.Ya("OPR")};
$a=function(){return(g.Ya("Chrome")||g.Ya("CriOS"))&&!Za()&&!g.Ya("Edge")};
g.bb=function(a){g.da.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.da.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.Ya("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.p)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.Ya("Trident")&&!g.Ya("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.ca(c.next)){c=c.next;var a=c.bp;c.bp=null;a()}};
return function(a){d.next={bp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.da.setTimeout(a,0)}};
g.cb=function(a,b,c){this.F=c;this.C=a;this.D=b;this.B=0;this.A=null};
g.db=function(a,b){a.D(b);a.B<a.F&&(a.B++,b.next=a.A,a.A=b)};
eb=function(){this.B=this.A=null};
fb=function(){this.next=this.scope=this.se=null};
g.lb=function(a,b){gb||laa();ib||(gb(),ib=!0);var c=jb,d=kb.get();d.set(a,b);c.B?c.B.next=d:c.A=d;c.B=d};
laa=function(){if(g.da.Promise&&g.da.Promise.resolve){var a=g.da.Promise.resolve(void 0);gb=function(){a.then(nb)}}else gb=function(){var a=nb;
!g.na(g.da.setImmediate)||g.da.Window&&g.da.Window.prototype&&!g.Ya("Edge")&&g.da.Window.prototype.setImmediate==g.da.setImmediate?(ob||(ob=kaa()),ob(a)):g.da.setImmediate(a)}};
nb=function(){for(var a=null;a=jb.remove();){try{a.se.call(a.scope)}catch(b){g.bb(b)}g.db(kb,a)}ib=!1};
g.pb=function(){this.Sc=this.Sc;this.Gb=this.Gb};
g.sb=function(a,b){g.qb(a,g.ra(g.rb,b))};
g.qb=function(a,b){a.Sc?b.call(void 0):(a.Gb||(a.Gb=[]),a.Gb.push(g.ca(void 0)?(0,g.p)(b,void 0):b))};
g.rb=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.tb=function(a){g.pb.call(this);this.D=1;this.B=[];this.C=0;this.A=[];this.wd={};this.F=Boolean(a)};
maa=function(a,b,c){g.lb(function(){a.apply(b,c)})};
g.wb=function(a){ub(g.vb,arguments)};
g.t=function(a,b){return a in g.vb?g.vb[a]:b};
g.yb=function(a,b){g.na(a)&&(a=g.xb(a));return window.setTimeout(a,b)};
g.zb=function(a,b){g.na(a)&&(a=g.xb(a));return window.setInterval(a,b)};
g.Ab=function(a){window.clearTimeout(a)};
g.Bb=function(a){window.clearInterval(a)};
g.xb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.Cb(b),b;}}:a};
g.Cb=function(a,b){var c=g.m("yt.logging.errors.log");c?c(a,b):(c=g.t("ERRORS",[]),c.push([a,b]),g.wb("ERRORS",c))};
g.Eb=function(a){return a in g.Db};
g.Fb=function(a,b,c){var d=b||{};if(a=a in g.Db?g.Db[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});
return a};
ub=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.Lb=function(a,b,c){var d=Gb();if(d){var e=d.subscribe(a,function(){if(!Hb||Hb!=e){var d=arguments,k=function(){Ib[e]&&b.apply(c||window,d)};
try{Jb[a]?k():g.yb(k,0)}catch(n){g.Cb(n)}}},c);
Ib[e]=!0;Kb[a]||(Kb[a]=[]);Kb[a].push(e);return e}return 0};
g.Mb=function(a){var b=Gb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.u)(a,function(a){b.unsubscribeByKey(a);delete Ib[a]}))};
g.v=function(a,b){var c=Gb();return c?c.publish.apply(c,arguments):!1};
g.Nb=function(a,b){Jb[a]=!0;var c=Gb(),c=c?c.publish.apply(c,arguments):!1;Jb[a]=!1;return c};
Gb=function(){return g.m("yt.pubsub.instance_")};
g.Ob=function(){return!!g.m("yt.scheduler.instance")};
g.Pb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.m("yt.scheduler.instance.addJob");return c?c(a,0,b):void 0===b?(a(),window.NaN):g.yb(a,b||0)};
g.Qb=function(a,b){return g.Pb(a,b)};
g.Rb=function(a){var b=g.m("yt.scheduler.instance.cancelJob");b?b(a):g.Ab(a)};
g.Sb=function(a){for(var b=0,c=a.length;b<c;b++)g.Rb(a[b])};
g.Tb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.G=d?g.xb(d):null;this.F=e?g.xb(e):null;this.D=[];this.A=this.B=0};
g.Ub=function(a){g.Rb(a.B);a.B=g.Qb((0,g.p)(a.init,a))};
g.Xb=function(a){a.name in Vb&&Wb(a.name);Vb[a.name]={reqs:[],disable:(0,g.p)(a.disable,a)};(0,g.u)(a.deps,function(b){if(!(b in Vb))throw Error("Module "+b+" required by "+a.name);Vb[b].reqs.push(a.name)});
a.enable()};
Wb=function(a){if(a in Vb){var b=Vb[a];(0,g.u)(b.reqs,function(a){Wb(a)});
try{b.disable()}catch(c){}delete Vb[a]}};
g.Zb=function(){this.A="";this.B=Yb};
g.$b=function(a){return a instanceof g.Zb&&a.constructor===g.Zb&&a.B===Yb?a.A:"type_error:Const"};
g.bc=function(){this.A="";this.B=ac};
g.cc=function(a){return a instanceof g.bc&&a.constructor===g.bc&&a.B===ac?a.A:"type_error:SafeStyle"};
g.dc=function(a){var b=new g.bc;b.A=a;return b};
g.fc=function(){this.A="";this.B=ec};
g.gc=function(a){return a instanceof g.fc&&a.constructor===g.fc&&a.B===ec?a.A:"type_error:SafeUrl"};
g.ic=function(a){if(a instanceof g.fc)return a;a=a.Mf?a.ue():String(a);naa.test(a)||(a="about:invalid#zClosurez");return g.hc(a)};
g.hc=function(a){var b=new g.fc;b.A=a;return b};
g.kc=function(){this.A="";this.B=jc};
g.lc=function(a){return a instanceof g.kc&&a.constructor===g.kc&&a.B===jc?a.A:"type_error:TrustedResourceUrl"};
g.nc=function(){this.A="";this.C=mc;this.B=null};
g.oc=function(a){return a instanceof g.nc&&a.constructor===g.nc&&a.C===mc?a.A:"type_error:SafeHtml"};
g.qc=function(a){if(a instanceof g.nc)return a;var b=null;a.mm&&(b=a.sg());a=g.wa(a.Mf?a.ue():String(a));return g.pc(a,b)};
g.tc=function(a,b,c){if(!rc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in oaa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return g.sc(a,b,c)};
g.uc=function(a){function b(a){g.ia(a)?(0,g.u)(a,b):(a=g.qc(a),d+=g.oc(a),a=a.sg(),0==c?c=a:0!=a&&c!=a&&(c=null))}
var c=0,d="";(0,g.u)(arguments,b);return g.pc(d,c)};
g.pc=function(a,b){var c=new g.nc;c.A=a;c.B=b;return c};
g.sc=function(a,b,c){var d=null,e="<"+a;if(b)for(var h in b){if(!rc.test(h))throw Error('Invalid attribute name "'+h+'".');var k=b[h];if(null!=k){var n,r=a;n=h;if(k instanceof g.Zb)k=g.$b(k);else if("style"==n.toLowerCase()){if(!g.oa(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+" given: "+k);if(!(k instanceof g.bc)){var r="",B=void 0;for(B in k){if(!/^[-_a-zA-Z0-9]+$/.test(B))throw Error("Name allows only [-_a-zA-Z0-9], got: "+B);var C=
k[B];if(null!=C){if(C instanceof g.Zb)C=g.$b(C);else if(paa.test(C)){for(var N=!0,V=!0,ea=0;ea<C.length;ea++){var ua=C.charAt(ea);"'"==ua&&V?N=!N:'"'==ua&&N&&(V=!V)}N&&V||(C="zClosurez")}else C="zClosurez";r+=B+":"+C+";"}}k=r?g.dc(r):qaa}k=g.cc(k)}else{if(/^on/i.test(n))throw Error('Attribute "'+n+'" requires goog.string.Const value, "'+k+'" given.');if(n.toLowerCase()in raa)if(k instanceof g.kc)k=g.lc(k);else if(k instanceof g.fc)k=g.gc(k);else if(g.la(k))k=g.ic(k).ue();else throw Error('Attribute "'+
n+'" on tag "'+r+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+k+'" given.');}k.Mf&&(k=k.ue());n=n+'="'+g.wa(String(k))+'"';e=e+(" "+n)}}null!=c?g.ia(c)||(c=[c]):c=[];!0===saa[a.toLowerCase()]?e+=">":(d=g.uc(c),e+=">"+g.oc(d)+"</"+a+">",d=d.sg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return g.pc(e,d)};
g.vc=function(a,b){a.innerHTML=g.oc(b)};
g.wc=function(a,b){var c;c=b instanceof g.fc?b:g.ic(b);a.href=g.gc(c)};
g.w=function(a,b){return a?a.dataset?a.dataset[g.xc(b)]:a.getAttribute("data-"+b):null};
g.yc=function(a,b){return a?a.dataset?g.xc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};
g.xc=function(a){return zc[a]||(zc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.Bc=function(a,b){var c=g.Ac(a);window.spf.script.load(a,c,b)};
g.Cc=function(a,b){var c=g.Ac(a);window.spf.script.ignore(c,b)};
g.Ac=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(taa,""),b=b.replace(uaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.Dc=function(a,b){this.x=g.ca(a)?a:0;this.y=g.ca(b)?b:0};
g.Ec=function(){return g.Ya("iPhone")&&!g.Ya("iPod")&&!g.Ya("iPad")};
vaa=function(){var a=g.Xa;if(g.Fc)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.Gc)return/Edge\/([\d\.]+)/.exec(a);if(g.x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Hc)return/WebKit\/(\S+)/.exec(a)};
Ic=function(){var a=g.da.document;return a?a.documentMode:void 0};
g.Lc=function(a){return Jc[a]||(Jc[a]=0<=g.Ba(g.Kc,a))};
g.Nc=function(a){return Number(g.Mc)>=a};
g.y=function(a){return g.la(a)?window.document.getElementById(a):a};
g.Oc=function(a){return g.la(a)?window.document.getElementById(a):a};
g.z=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=g.Pc(window.document,"*",a,b)[0];return d||null};
g.Pc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,h=0,k;k=a[h];h++)b==k.nodeName&&(d[e++]=k);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(h=e=0;k=a[h];h++)b=k.className,"function"==typeof b.split&&g.Ia(b.split(/\s+/),c)&&(d[e++]=k);d.length=e;return d}return a};
g.Rc=function(a,b){g.Pa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Qc.hasOwnProperty(d)?a.setAttribute(Qc[d],b):g.ta(d,"aria-")||g.ta(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.Tc=function(a){var b=g.Sc(a);a=a.parentWindow||a.defaultView;return g.x&&g.Lc("10")&&a.pageYOffset!=b.scrollTop?new g.Dc(b.scrollLeft,b.scrollTop):new g.Dc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Sc=function(a){return a.scrollingElement?a.scrollingElement:!g.Hc&&g.Uc(a)?a.documentElement:a.body||a.documentElement};
g.Wc=function(a,b,c){return g.Vc(window.document,arguments)};
g.Vc=function(a,b){var c=b[0],d=b[1];if(!waa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.wa(d.name),'"');if(d.type){c.push(' type="',g.wa(d.type),'"');var e={};g.Wa(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.la(d)?c.className=d:g.ia(d)?c.className=d.join(" "):g.Rc(c,d));2<b.length&&g.Xc(a,c,b,2);return c};
g.Xc=function(a,b,c,d){function e(c){c&&b.appendChild(g.la(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var h=c[d];!g.ka(h)||g.oa(h)&&0<h.nodeType?e(h):(0,g.u)(xaa(h)?g.Ma(h):h,e)}};
g.Uc=function(a){return"CSS1Compat"==a.compatMode};
g.Yc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.$c=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.ad=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
yaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
zaa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.bd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
xaa=function(a){if(a&&"number"==typeof a.length){if(g.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.na(a))return"function"==typeof a.item}return!1};
g.cd=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.dd=function(a,b,c,d,e,h,k){var n="";a&&(n+=a+":");c&&(n+="//",b&&(n+=b+"@"),n+=c,d&&(n+=":"+d));e&&(n+=e);h&&(n+="?"+h);k&&(n+="#"+k);return n};
g.fd=function(a){return a?(0,window.decodeURI)(a):a};
g.hd=function(a,b){return b.match(g.gd)[a]||null};
g.id=function(a){return g.fd(g.hd(3,a))};
g.jd=function(a){a=a.match(g.gd);return g.dd(null,null,null,null,a[5],a[6],a[7])};
g.kd=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.ld=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.md=function(a,b,c){if(g.ia(b))for(var d=0;d<b.length;d++)g.md(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.va(b))};
nd=function(a,b){for(var c in b)g.md(c,b[c],a);return a};
g.od=function(a){a=nd([],a);a[0]="";return a.join("")};
g.pd=function(a,b){return g.ld(nd([a],b))};
g.qd=function(a,b,c){a&&(c?a&&(a=g.Wc("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.bd(a).body.appendChild(a)):Aaa(a,b))};
g.rd=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.qd(a,void 0)}catch(b){g.qd(a,void 0)}};
Aaa=function(a,b){var c=new window.Image,d=""+Baa++;sd[d]=c;c.onload=c.onerror=function(){b&&sd[d]&&b();delete sd[d]};
c.src=a};
g.td=function(a,b){this.version=a;this.args=b};
g.ud=function(a,b){this.topic=a;this.uf=b};
g.wd=function(a,b){var c=g.vd();return c?c.publish.call(c,a.toString(),a,b):!1};
g.vd=function(){return g.m("yt.pubsub2.instance_")};
xd=function(a){g.td.call(this,1,arguments)};
g.Cd=function(a,b,c){yd(c)[a]=b||(0,g.zd)();b||Ad(a);Bd(!1,c)};
Ed=function(a,b){Dd(void 0).yt_sts=a;g.Cd("_start",b,void 0)};
Gd=function(a){Fd(a);Caa();g.l("yt.timing.pingSent_",!1,void 0)};
Hd=function(a){a=yd(a);if(a.aft)return a.aft;for(var b=g.t("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
Jd=function(a,b){var c=b||Id(void 0).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};
Ld=function(a){return Math.round(Kd.timing.navigationStart+a)};
Daa=function(a){var b=window.location.protocol,c=Kd.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=Ld(d.startTime),a.wfce=Ld(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=Ld(c.startTime),a.wffe=Ld(c.responseEnd))};
Od=function(a){var b=yd(a),c=Id(a).span,d=Dd(a),e=g.m("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))Md(e),Gd(a)}else{var h=g.t("CSI_SERVICE_NAME","youtube"),e={v:2,s:h,action:g.t("TIMING_ACTION",void 0)};if(Kd.now&&Kd.timing){var k=Kd.timing.navigationStart+Kd.now(),k=Math.round((0,g.zd)()-k);d.yt_hrd=k}var k=g.t("TIMING_INFO",{}),n;for(n in k)d[n]=k[n];n=d.srt;delete d.srt;var r;n||0===n||(r=Kd.timing||{},n=Math.max(0,r.responseStart-r.navigationStart),(0,window.isNaN)(n)&&d.pt&&(n=d.pt));if(n||
0===n)d.srt=n;d.h5jse&&(k=window.location.protocol+g.m("ytplayer.config.assets.js"),(k=Kd.getEntriesByName?Kd.getEntriesByName(k)[0]:null)?d.h5jse=Math.round(d.h5jse-k.responseEnd):delete d.h5jse);b.aft=Hd(a);k=b._start;if("cold"==d.yt_lt){r||(r=Kd.timing||{});var B;a:if(B=r,B.msFirstPaint)B=Math.max(0,B.msFirstPaint);else{var C=window.chrome;if(C&&(C=C.loadTimes,g.na(C))){var C=C(),N=1E3*Math.min(C.requestTime||window.Infinity,C.startLoadTime||window.Infinity),N=window.Infinity===N?0:B.navigationStart-
N;B=Math.max(0,Math.round(1E3*C.firstPaintTime+N)||0);break a}B=0}0<B&&B>k&&(b.fpt=B);Jd(r,c);Kd.getEntriesByType&&Daa(b)}C=yd(a);r=C.pbr;B=C.vc;C=C.pbs;r&&B&&C&&r<B&&B<C&&1==Dd(a).yt_vis&&"youtube"==h&&(Dd(a).yt_lt="hot_bg",h=b.vc,r=b.pbs,delete b.aft,c.aft=Math.round(r-h));(h=g.t("PREVIOUS_ACTION"))&&(d.pa=h);d.p=g.t("CLIENT_PROTOCOL")||"unknown";d.t=g.t("CLIENT_TRANSPORT")||"unknown";window.navigator&&window.navigator.sendBeacon&&(d.ba=1);for(var V in d)"_"!=V.charAt(0)&&(e[V]=d[V]);b.ps=(0,g.zd)();
d={};V=[];for(var ea in b)"_"!=ea.charAt(0)&&(B=Math.max(Math.round(b[ea]-k),0),d[ea]=B,V.push(ea+"."+B));e.rt=V.join(",");b=e;ea=[];for(var ua in c)"_"!=ua.charAt(0)&&ea.push(ua+"."+c[ua]);b.it=ea.join(",");(ua=g.m("ytdebug.logTiming"))&&ua(e,d,c);Gd(a);g.t("EXP_DEFER_CSI_PING")?(Nd(),g.l("yt.timing.deferredPingArgs_",e,void 0),a=g.yb(Nd,0),g.l("yt.timing.deferredPingTimer_",a,void 0)):Md(e);g.wd(Eaa,new xd(d.aft+(n||0)))}};
Bd=function(a,b){var c=g.t("TIMING_ACTION",void 0),d=yd(b);if(g.m("yt.timing.ready_")&&c&&d._start&&Hd(b)){var c=!0,e=g.t("TIMING_WAIT",[]);if(!a&&e.length)for(var h=0,k=e.length;h<k;++h)if(!(e[h]in d)){c=!1;break}(c||b)&&Od(b)}};
Md=function(a){if(g.t("DEBUG_CSI_DATA")){var b=g.m("yt.timing.csiData");b||(b=[],g.l("yt.timing.csiData",b,void 0));b.push({page:window.location.href,time:new Date,args:a})}g.t("EXP_DEFER_CSI_PING")&&(g.Ab(g.m("yt.timing.deferredPingTimer_")),g.l("yt.timing.deferredPingArgs_",null,void 0));var c="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c=g.t("CSI_LOG_WITH_YT")?"/csi_204":c,b="",d;for(d in a)b+="&"+d+"="+a[d];a=c+"?"+b.substring(1);b=g.t("DOUBLE_LOG_CSI")?
"/csi_204?"+b.substring(1):null;window.navigator&&window.navigator.sendBeacon?(g.rd(a),b&&g.rd(b)):(g.qd(a),b&&g.qd(b));g.l("yt.timing.pingSent_",!0,void 0)};
Nd=function(a){if(g.t("EXP_DEFER_CSI_PING")){var b=g.m("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),Md(b))}};
yd=function(a){return Id(a).tick};
Dd=function(a){return Id(a).info};
Id=function(a){return g.m("ytcsi."+(a||"")+"data_")||Fd(a)};
Fd=function(a){var b={tick:{},span:{},info:{}};g.l("ytcsi."+(a||"")+"data_",b,void 0);return b};
Pd=function(a){g.m("yt.timing.pingSent_")||(g.Cd("aa"),Dd(void 0).ap=1,Dd(void 0).yt_fss=a,Od())};
Faa=function(a){a=g.Qd(a);return g.Rd(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
g.Rd=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
g.Qd=function(a){a=g.id(a);return null===a?null:a.split(".").reverse()};
g.Sd=function(a,b){g.qd("/gen_204?"+a,b)};
g.Td=function(a){if(a.classList)return a.classList;a=a.className;return g.la(a)&&a.match(/\S+/g)||[]};
g.A=function(a,b){return a.classList?a.classList.contains(b):g.Ia(g.Td(a),b)};
g.D=function(a,b){a.classList?a.classList.add(b):g.A(a,b)||(a.className+=0<a.className.length?" "+b:b)};
g.E=function(a,b){a.classList?a.classList.remove(b):g.A(a,b)&&(a.className=(0,g.Ud)(g.Td(a),function(a){return a!=b}).join(" "))};
g.Vd=function(a,b,c){c?g.D(a,b):g.E(a,b)};
g.Wd=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.u)(a.childNodes,function(a){b.appendChild(g.Wd(a))}):b.innerHTML=a.innerHTML;
return b};
g.Xd=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Gaa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.Tm=a.pageX;this.Um=a.pageY}};
g.Zd=function(a,b,c,d){return g.Ra(g.Yd,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.F=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.Zd(a,b,c,d);if(e)return e;var e=++$d.count+"",h=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=h?function(d){d=new g.Xd(d);if(!g.cd(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.Xd(b);
b.currentTarget=a;return c.call(a,b)};
k=g.xb(k);g.Yd[e]=[a,b,c,k,d];a.addEventListener?"mouseenter"==b&&h?a.addEventListener("mouseover",k,d):"mouseleave"==b&&h?a.addEventListener("mouseout",k,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",k,d):a.addEventListener(b,k,d):a.attachEvent("on"+b,k);return e};
g.ae=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.ce=function(){if(null==g.m("_lact",window)){var a=(0,window.parseInt)(g.t("LACT"),10),a=(0,window.isFinite)(a)?(0,g.zd)()-Math.max(a,0):-1;g.l("_lact",a,window);-1==a&&be();g.F(window.document,"keydown",be);g.F(window.document,"keyup",be);g.F(window.document,"mousedown",be);g.F(window.document,"mouseup",be);g.Lb("page-mouse",be);g.Lb("page-scroll",be);g.Lb("page-resize",be)}};
be=function(){null==g.m("_lact",window)&&(g.ce(),g.m("_lact",window));var a=(0,g.zd)();g.l("_lact",a,window);g.v("USER_ACTIVE")};
g.de=function(){var a=g.m("_lact",window);return null==a?-1:Math.max((0,g.zd)()-a,0)};
ee=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Ua(Haa);this.assets=a.assets||{};this.attrs=a.attrs||g.Ua(Iaa);this.params=a.params||g.Ua(Jaa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.fe=function(a){a instanceof ee||(a=new ee(a));return a};
he=function(){return null!=g.ge};
g.ie=function(){return g.ge?g.ge.invoke():null};
je=function(){return(0,window.parseInt)(g.t("DCLKSTAT",0),10)};
g.ke=function(a,b){this.A=a;this.B=b};
g.le=function(a){this.A=a};
g.ne=function(a){a=(a.A.cookie||"").split(g.me);for(var b=[],c=[],d,e,h=0;e=a[h];h++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.pe=function(a,b,c,d){g.oe.set(""+a,b,c,"/",d||"youtube.com")};
g.qe=function(a,b){return g.oe.get(""+a,b)};
g.te=function(a,b,c){var d=g.t("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.id(window.location.href);e&&d.push(e);e=g.id(a);if(g.Ia(d,e)||!e&&g.ta(a,"/"))if(a=g.jd(a),a=g.kd(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(re(a,b,c),se(b))):(re(a,b),se(b))};
re=function(a,b,c){a=g.t("SMALLER_SESSION_TEMPDATA_NAME")?"ST-"+g.Ca(a).toString(36):"s_tempdata-"+g.Ca(a);c=c||5;b=b?g.od(b):"";g.pe(a,b,c)};
se=function(a){if(a){a=a.itct||a.ved;var b=g.m("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.ke(a))}};
g.ue=function(a,b,c){c=c||"";g.wc(window.location,g.pd(a,b||{})+c)};
g.ve=function(a,b){b&&g.te(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.ue(a)};
g.we=function(a,b,c){var d=g.t("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.te(a,b);if(c)return!1;g.ve(a);return!0};
g.ye=function(){return g.Hc?"Webkit":g.Fc?"Moz":g.x?"ms":g.xe?"O":null};
g.ze=function(){return g.Hc?"-webkit":g.Fc?"-moz":g.x?"-ms":g.xe?"-o":null};
g.Ae=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.Be=function(a,b){return a&&b?b instanceof g.Ae?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.De=function(a,b){var c=Ce[b];if(!c){var d=g.Da(b),c=d;void 0===a.style[d]&&(d=g.ye()+g.Ea(d),void 0!==a.style[d]&&(c=d));Ce[b]=c}return c};
g.Ee=function(a,b){var c=a.style[g.Da(b)];return"undefined"!==typeof c?c:a.style[g.De(a,b)]||""};
g.Fe=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.Ge=function(a,b){a.style.height=g.Fe(b,!0)};
g.He=function(a,b){a.style.width=g.Fe(b,!0)};
g.Ie=function(a,b){a.style.display=b?"":"none"};
g.Ke=function(){var a=g.qe("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(g.Je[d]=c.toString())}};
Le=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
Me=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};
g.Ne=function(a){a=void 0!==g.Je[a]?g.Je[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};
g.Oe=function(a,b){return!!((g.Ne("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
g.Pe=function(a,b){(a=g.y(a))&&a.style&&(g.Ie(a,b),g.Vd(a,"hid",!b))};
g.Qe=function(a){return(a=g.y(a))?!("none"==a.style.display||g.A(a,"hid")):!1};
Kaa=function(a){if(a=g.y(a))g.Qe(a)?(g.Ie(a,!1),g.D(a,"hid")):(g.Ie(a,!0),g.E(a,"hid"))};
g.G=function(a){(0,g.u)(arguments,function(a){!g.ka(a)||a instanceof window.Element?g.Pe(a,!0):(0,g.u)(a,function(a){g.G(a)})})};
g.H=function(a){(0,g.u)(arguments,function(a){!g.ka(a)||a instanceof window.Element?g.Pe(a,!1):(0,g.u)(a,function(a){g.H(a)})})};
g.Re=function(a){(0,g.u)(arguments,function(a){g.ka(a)?(0,g.u)(a,function(a){g.Re(a)}):Kaa(a)})};
g.Te=function(){this.A=this.minor=this.major=0;this.B="";var a=g.m("window.navigator.plugins"),b=g.m("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,h=c.length;e<h;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.B=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,n,r,B;if(g.Se)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(C){k=null}else r=window.document.body,B=window.document.createElement("object"),B.setAttribute("type","application/x-shockwave-flash"),k=r.appendChild(B);if(k&&"GetVariable"in k)try{n=k.GetVariable("$version")}catch(C){n=""}r&&B&&r.removeChild(B);(k=n||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
Ue=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
Ve=function(a){return-1<a.B.indexOf("Gnash")&&-1==a.B.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
Laa=function(a){return g.We?!Ue(a,11,2):g.Xe?!Ue(a,11,3):!Ve(a)};
Ye=function(a,b,c){if(b){a=g.la(a)?g.Oc(a):a;var d=g.Ua(c.attrs);d.tabindex=0;var e=g.Ua(c.params);e.flashvars=g.od(c.args);if(g.Se){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var h in d)b.setAttribute(h,d[h]);for(h in e)d=window.document.createElement("param"),d.setAttribute("name",h),d.setAttribute("value",e[h]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(h in d)b.setAttribute(h,d[h]);for(h in e)b.setAttribute(h,e[h])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.af=function(a,b){a=g.la(a)?g.Oc(a):a;b=g.fe(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=g.Te.getInstance();Ue(c,b.minVersion)?(c=Ze(b,c),Ye(a,c,b)):$e(a,b,c)};
bf=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=g.fe(a);var d=!!b,e=g.y(a.attrs.id),h=e?e.parentNode:null;if(e&&h){if(window!=window.top){var k=null;if(window.document.referrer){var n=window.document.referrer.substring(0,128);Faa(n)||(k=n)}else k="unknown";k&&(d=!0,a.args.framer=k)}k=g.Te.getInstance();if(Ue(k,a.minVersion)){var n=Ze(a,k),r="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(r=e.getAttribute("src")||e.movie);(r!=n||d)&&Ye(h,n,a);Laa(k)&&Maa()}else $e(h,a,k);c&&c()}else g.yb(function(){bf(a,
b,c)},50)}};
$e=function(a,b,c){0==c.major&&b.fallback?b.fallback():0==c.major&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+g.Fb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};
Ze=function(a,b){var c;(c=Ve(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Ue(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
Maa=function(){var a=g.y("flash10-promo-div"),b=g.Oe(g.Ke.getInstance(),107);a&&!b&&g.G(a)};
g.cf=function(a,b){var c=a.match(Naa);window.spf.style.load(a,c?c[1]:"",b)};
g.df=function(a){g.pb.call(this);this.A=[];this.B=a||this};
ef=function(a,b,c,d){d=g.xb((0,g.p)(d,a.B));b.addEventListener(c,d);a.A.push({target:b,name:c,Zb:d})};
ff=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Zb)}};
jf=function(a,b){g.pb.call(this);this.X=this.F=a;this.aa=b;this.P=!1;this.B={};this.ab=this.Y=null;this.ga=new g.tb;g.sb(this,this.ga);this.D={};this.G=this.eb=this.C=this.xb=this.A=null;this.ka=!1;this.J=this.L=this.T=this.ia=null;this.gb={};this.tc=["onReady"];this.qa=new g.df(this);g.sb(this,this.qa);this.Ib=null;this.Ub=0;this.Ra={};gf(this);this.le("onDetailedError",(0,g.p)(this.pH,this));this.le("onTabOrderChange",(0,g.p)(this.Fx,this));this.le("onTabAnnounce",(0,g.p)(this.Eo,this));this.le("WATCH_LATER_VIDEO_ADDED",
(0,g.p)(this.tH,this));this.le("WATCH_LATER_VIDEO_REMOVED",(0,g.p)(this.uH,this));g.hf||(this.le("onMouseWheelCapture",(0,g.p)(this.YG,this)),this.le("onMouseWheelRelease",(0,g.p)(this.ZG,this)));this.le("onAdAnnounce",(0,g.p)(this.Eo,this));this.O=new g.df(this);g.sb(this,this.O);this.qb=!1;this.lb=null};
lf=function(a,b){a.xb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.aa,a.A.attrs.id=a.aa);a.X.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.aa;a.eb||(a.eb=kf(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.He(a.X,Number(c)||c);(c=a.A.attrs.height)&&g.Ge(a.X,Number(c)||c)};
mf=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.B.loadVideoByPlayerVars(a.A.args):a.B.cueVideoByPlayerVars(a.A.args))};
nf=function(a){if(!g.ca(a.A.disable.flash)){var b=a.A.disable,c;c=Ue(g.Te.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
qf=function(a){var b;if(!(b=!a.A.html5&&nf(a))){if(!g.ca(a.A.disable.html5)){var c;b=!0;void 0!=a.A.args.deviceHasDisplay&&(b=a.A.args.deviceHasDisplay);if(2.2==of)c=!0;else{a:{var d=b;b=g.m("yt.player.utils.videoElement_");b||(b=window.document.createElement("video"),g.l("yt.player.utils.videoElement_",b,void 0));try{if(b.canPlayType)for(var d=d?Oaa:Paa,e=0;e<d.length;e++)if(b.canPlayType(d[e])){c=null;break a}c="fmt.noneavailable"}catch(h){c="html5.missingapi"}}c=!c}c&&(c=pf(a)||a.A.assets.js);
a.A.disable.html5=!c;c||(a.A.args.html5_unavailable="1")}b=!!a.A.disable.html5}return b?nf(a)?"flash":"unsupported":"html5"};
tf=function(a,b){if(!b||(5!=(Qaa[b.errorCode]||5)?0:-1!=Raa.indexOf(b.errorCode))){var c=rf(a);c&&c.stopVideo&&c.stopVideo();if(nf(a)){var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.fe(c));d.args.autoplay=1;d.args.html5_unavailable="1";lf(a,d);sf(a,"flash")}}};
sf=function(a,b){a.isDisposed()||(b||(b=qf(a)),("flash"==b?a.JM:"html5"==b?a.KM:a.LM).call(a))};
pf=function(a){var b=!0,c=rf(a);c&&a.A&&(a=a.A,b=g.w(c,"version")==a.assets.js);return b&&!!g.m("yt.player.Application.create")};
rf=function(a){var b=g.y(a.C);!b&&a.X&&a.X.querySelector&&(b=a.X.querySelector("#"+a.C));return b};
uf=function(a,b,c){var d=b[c];return function(){try{return a.Ib=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.Ib=e,g.Cb(e,"WARNING"))}}};
gf=function(a){a.P=!1;if(a.ab)for(var b in a.D)a.ab(b,a.D[b]);for(var c in a.Ra)g.Ab((0,window.parseInt)(c,10));a.Ra={};a.Y=null;a.ab=null;for(var d in a.B)a.B[d]=null;a.B.addEventListener=(0,g.p)(a.le,a);a.B.removeEventListener=(0,g.p)(a.aL,a);a.B.destroy=(0,g.p)(a.dispose,a);a.B.getLastError=(0,g.p)(a.Py,a);a.B.getPlayerType=(0,g.p)(a.dz,a);a.B.getCurrentVideoConfig=(0,g.p)(a.ty,a);a.B.loadNewVideoConfig=(0,g.p)(a.$n,a);a.B.isReady=(0,g.p)(a.YM,a)};
kf=function(a,b){var c=b;if("string"==typeof b){if(a.gb[b])return a.gb[b];c=function(){var a=g.m(b);a&&a.apply(g.da,arguments)};
a.gb[b]=c}return c?c:null};
Saa=function(a,b){var c="ytPlayer"+b+a.aa;a.D[b]=c;g.da[c]=function(c){var e=g.yb(function(){a.isDisposed()||(a.ga.na(b,c),g.Sa(a.Ra,String(e)))},0);
g.Ta(a.Ra,String(e),!0)};
return c};
vf=function(a){return(a=rf(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
wf=function(a){g.Cd("dcp");a.cancel();gf(a);a.G=null;a.A&&(a.A.loaded=!1);var b=rf(a);"html5"==vf(a)?a.T=b:b&&b.destroy&&b.destroy();g.Yc(a.F);ff(a.qa);a.L=null;a.J=null};
g.zf=function(a,b){a=g.la(a)?g.Oc(a):a;b=g.fe(b);var c=g.xf+"_"+g.qa(a),d=g.yf[c];if(d)return d.$n(b),d.B;d=new jf(a,c);g.yf[c]=d;g.v("player-added",d.B);g.qb(d,g.ra(Taa,d));g.yb(function(){d.$n(b)},0);
return d.B};
Taa=function(a){g.yf[a.getId()]=null};
g.Af=function(a){a=g.y(a);if(!a)return null;var b=g.xf+"_"+g.qa(a),c=g.yf[b];c||(c=new jf(a,b),g.yf[b]=c);return c.B};
g.Bf=function(){return g.A(g.y("page-container"),"remote-connected")};
Uaa=function(){g.l("yt.abuse.botguardInitialized",he,void 0);g.l("yt.abuse.invokeBotguard",g.ie,void 0);g.l("yt.abuse.dclkstatus.checkDclkStatus",je,void 0);g.l("yt.player.exports.navigate",g.we,void 0);g.l("yt.player.embed",g.zf,void 0);g.l("yt.player.getPlayerByElement",g.Af,void 0);g.l("yt.util.activity.init",g.ce,void 0);g.l("yt.util.activity.getTimeSinceActive",g.de,void 0);g.l("yt.util.activity.setTimestamp",be,void 0);var a=g.m("ytplayer.config");Cf(a);g.m("ytspf.enabled")&&(Df=g.zb(Ef,5E3),
(a=g.Ff())?(a.addEventListener("onReady",Ef),a.addEventListener("onStateChange",Ef)):Gf("unable to init PP monitor"))};
Cf=function(a){for(var b in g.yf){var c=g.yf[b];c&&c.cancel()}if(a=a||null){b=g.Ff();var d=!0,c=g.Hf;g.Hf=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(If="",g.zf("player-api",a)):b.playVideo();a=g.fe(a);a.loaded=!0}Ef();g.l("ytplayer.config",a,void 0)};
g.Ff=function(){var a=g.m("yt.player.getPlayerByElement");return a?a("player-api"):null};
Ef=function(){var a=g.Ff();if(a){var b;b=g.y("player");b=!b||g.A(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.t("PAGE_NAME"),e=g.Bf();!c||d||e||(Gf("PP playing off watch (paused)"),a.pauseVideo());b&&d?Gf("PP off-screen on watch"):b||d||Gf("PP !off-screen off watch")}};
Gf=function(a){var b=g.t("PAGE_NAME");b&&(b=[b,If,g.m("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.l("yt.www.persistentplayer.issue",a,void 0),g.Cb(Error(a),"WARNING"))};
Kf=function(){g.Cd("ol");g.t("CSI_TICK_PAINT_TIME")?window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.Cd("cpt");Jf()},0)}):window.document.hidden?(g.Cd("cpt"),Jf()):(0,window.setTimeout)(function(){g.Cd("cpt");
Jf()},0):Jf()};
Jf=function(){Lf("init");var a=g.t("PAGE_NAME",void 0);a&&Lf("init-"+a)};
Lf=function(a){g.Ob()?Mf.push(g.Pb(g.ra(g.Nb,a),0)):g.v(a)};
Nf=function(){g.Sb(Mf);Mf.length=0;var a=g.t("PAGE_NAME",void 0);a&&g.Nb("dispose-"+a);g.Nb("dispose")};
Vaa=function(){Kf()};
Waa=function(){g.t("TIMING_REPORT_ON_UNLOAD")&&Bd(!0);g.t("CSI_MORE")&&Pd("u");Nd("u");Nf();g.Nb("pageunload")};
Xaa=function(a,b,c,d,e){for(var h=window.document.getElementsByTagName("script"),k=!1,n=0,r=h.length;n<r;n++)if(0<h[n].src.indexOf("/debug-")){k=!0;break}k&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.Cb(e))};
Sf=function(){Of=1;Pf=Qf=0;g.t("TIMING_REPORT_ON_UNLOAD")&&Bd(!0);g.t("CSI_MORE")&&Pd("n");Nd("n");Gd();Ed("n");Ad("mark_navigation_requested");Rf(Yaa);g.Nb("navigate")};
Wf=function(a){a=a.detail.part||a.detail.partial;g.Cd("nc"+Qf);++Qf;if(!a.data||!a.data.deferDispose){var b=1==Of;Of=2;b?(Rf(Zaa),Tf()):Rf($aa);if(b=a.data&&a.data.swfcfg)Uf(a.timing,b.args),Vf(b)}};
Xf=function(){g.Cd("np"+Pf);++Pf};
Yf=function(a){a=a.detail.response;var b=1==Of;Of=3;b&&(Rf(aba),Tf());if(b=a.data&&a.data.swfcfg)Uf(a.timing,b.args),Vf(b)};
ag=function(a){g.Cd("nd");a=a.detail.response;g.Zf=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;Dd(void 0).yt_nav=b;Ed("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);Dd(void 0).srt=b;var c=(b=!!a.spfCached)?"hot":"warm";Dd(void 0).yt_lt=c;var c=!!a.spfPrefetched,d=+c;Dd(void 0).yt_pft=d;d=a.responseStart-a.fetchStart;Id(void 0).span.preq=d;"redirectStart"in a&&Jd(a);Rf($f);window.document.getElementById("content").style.height="";g.t("EXP_LACT_HISTORY")&&
b&&!c&&be();Kf();Of=0};
bg=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.Cb(a)};
cg=function(a){g.Sd(g.od({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
cba=function(){bba()};
dba=function(){};
Tf=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Nf();var a=g.t("TIMING_ACTION"),b;for(b in g.vb)delete g.vb[b];g.wb("PREVIOUS_ACTION",a);g.l("ytplayer.config",null,void 0);if((b=g.Ff())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())If=b,(b=g.y("movie_player"))&&b.stopVideo?(b.stopVideo(),If="recovered"):If="missing2"}else If="missing";Ef()};
Vf=function(a){"cfg"in yd(void 0)||g.Cd("cfg");Cf(a)};
Rf=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Rb(dg);dg=g.Qb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var h=b.style;h.transitionDuration=h.webkitTransitionDuration=c+"ms";h.width=d+"%";g.Ab(eg);eg=g.yb(function(){b.className=e},c)},0)};
bba=function(){var a=$f[0]+50;g.Ab(eg);eg=g.yb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
Uf=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.u)(eba,function(a){a in b&&(delete b[a],e.push(a))});
g.t("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.Sd(g.od(c)))};
fg=function(){g.Tb.call(this,"www/base");this.C=0};
gg=function(a){(a=a.detail.name)&&Wb(a)};
g.aa=[];g.hg=g.hg||{};g.da=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.zd=Date.now||function(){return+new Date};g.sa[" "]=g.fa;var eaa,faa,gaa,haa,iaa,jaa,daa;g.za=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.ig=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.fba=2147483648*Math.random()|0;g.Ha=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.la(a))return g.la(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.gba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.la(a))return g.la(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)h in e&&b.call(c,e[h],h,a)};
g.Ud=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],h=0,k=g.la(a)?a.split(""):a,n=0;n<d;n++)if(n in k){var r=k[n];
b.call(c,r,n,a)&&(e[h++]=r)}return e};
g.jg=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),h=g.la(a)?a.split(""):a,k=0;k<d;k++)k in h&&(e[k]=b.call(c,h[k],k,a));
return e};
g.kg=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.p)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.u)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.lg=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return!0;
return!1};
g.mg=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&!b.call(c,e[h],h,a))return!1;
return!0};g.ng=g.Na(!1);g.og=g.Na(!0);g.pg=g.Na(null);var Va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var qg=g.da.navigator;if(qg){var rg=qg.userAgent;if(rg){g.Xa=rg;break a}}g.Xa=""};var ob;g.cb.prototype.get=function(){var a;0<this.B?(this.B--,a=this.A,this.A=a.next,a.next=null):a=this.C();return a};var kb=new g.cb(function(){return new fb},function(a){a.reset()},100);
eb.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.B=null),a.next=null);return a};
fb.prototype.set=function(a,b){this.se=a;this.scope=b;this.next=null};
fb.prototype.reset=function(){this.next=this.scope=this.se=null};var gb,ib=!1,jb=new eb;g.pb.prototype.Sc=!1;g.pb.prototype.isDisposed=function(){return this.Sc};
g.pb.prototype.dispose=function(){this.Sc||(this.Sc=!0,this.W())};
g.pb.prototype.W=function(){if(this.Gb)for(;this.Gb.length;)this.Gb.shift()()};g.q(g.tb,g.pb);g.f=g.tb.prototype;g.f.subscribe=function(a,b,c){var d=this.wd[a];d||(d=this.wd[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.f.unsubscribe=function(a,b,c){if(a=this.wd[a]){var d=this.A;if(a=g.Ga(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.xd(a)}return!1};
g.f.xd=function(a){var b=this.A[a];if(b){var c=this.wd[b];0!=this.C?(this.B.push(a),this.A[a+1]=g.fa):(c&&g.La(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.f.na=function(a,b){var c=this.wd[a];if(c){for(var d=Array(arguments.length-1),e=1,h=arguments.length;e<h;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.C++;try{for(e=0,h=c.length;e<h;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.C--,0<this.B.length&&0==this.C)for(;c=this.B.pop();)this.xd(c)}}return 0!=e}return!1};
g.f.clear=function(a){if(a){var b=this.wd[a];b&&((0,g.u)(b,this.xd,this),delete this.wd[a])}else this.A.length=0,this.wd={}};
g.f.rb=g.ba(1);g.f.W=function(){g.tb.N.W.call(this);this.clear();this.B.length=0};g.vb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.l("yt.config_",g.vb,void 0);g.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Db=window.yt&&window.yt.msgs_||g.m("window.ytcfg.msgs")||{};g.l("yt.msgs_",g.Db,void 0);g.Se="Microsoft Internet Explorer"==window.navigator.appName;var hba=g.m("yt.pubsub.instance_")||new g.tb;g.tb.prototype.subscribe=g.tb.prototype.subscribe;g.tb.prototype.unsubscribeByKey=g.tb.prototype.xd;g.tb.prototype.publish=g.tb.prototype.na;g.tb.prototype.clear=g.tb.prototype.clear;g.l("yt.pubsub.instance_",hba,void 0);var Ib=g.m("yt.pubsub.subscribedKeys_")||{};g.l("yt.pubsub.subscribedKeys_",Ib,void 0);var Kb=g.m("yt.pubsub.topicToKeys_")||{};g.l("yt.pubsub.topicToKeys_",Kb,void 0);var Jb=g.m("yt.pubsub.isSynchronous_")||{};
g.l("yt.pubsub.isSynchronous_",Jb,void 0);var Hb=g.m("yt.pubsub.skipSubId_")||null;g.l("yt.pubsub.skipSubId_",Hb,void 0);g.f=g.Tb.prototype;g.f.mL=function(){this.Gj()||this.init()};
g.f.enable=function(){this.A=1;(0,g.u)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.mL,this),this.subscribe("dispose-"+a,this.dispose,this),g.t("PAGE_NAME")==a&&g.Ub(this))},this)};
g.f.init=function(){g.Rb(this.B);this.A=2;this.G&&this.G()};
g.f.Gj=function(){return 2==this.A};
g.f.dispose=function(){this.A=3;g.Rb(this.B);this.F&&this.F()};
g.f.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.Cb(a)}};
g.f.subscribe=function(a,b,c){a=g.Lb(a,b,c);this.D.push(a);return a};
g.f.clear=function(){g.Mb(this.D);this.D=[]};var Vb=g.m("yt.modules.registry_")||{};g.l("yt.modules.registry_",Vb,void 0);var saa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};g.iba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.jba=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");g.Zb.prototype.Mf=!0;g.Zb.prototype.ue=function(){return this.A};
g.Zb.prototype.toString=function(){return"Const{"+this.A+"}"};
var Yb={};g.bc.prototype.Mf=!0;var ac={};g.bc.prototype.ue=function(){return this.A};
var qaa=g.dc(""),paa=/^([-,."'%_!# a-zA-Z0-9]+|(?:rgb|hsl)a?\([0-9.%, ]+\))$/;g.fc.prototype.Mf=!0;g.fc.prototype.ue=function(){return this.A};
g.fc.prototype.mm=!0;g.fc.prototype.sg=function(){return 1};
var naa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,ec={};g.hc("about:blank");g.kc.prototype.Mf=!0;g.kc.prototype.ue=function(){return this.A};
g.kc.prototype.mm=!0;g.kc.prototype.sg=function(){return 1};
var jc={};var rc,raa,oaa,mc;g.nc.prototype.mm=!0;g.nc.prototype.sg=function(){return this.B};
g.nc.prototype.Mf=!0;g.nc.prototype.ue=function(){return this.A};
rc=/^[a-zA-Z0-9-]+$/;raa={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};oaa={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};mc={};g.kba=g.pc("<!DOCTYPE html>",0);g.sg=g.pc("",0);g.tg=g.pc("<br>",0);var zc={};var taa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,uaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.lba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.f=g.Dc.prototype;g.f.clone=function(){return new g.Dc(this.x,this.y)};
g.f.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.f.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.f.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.f.scale=function(a,b){var c=g.ma(b)?b:a;this.x*=a;this.y*=c;return this};var vg,Jc,wg;g.xe=Za();g.x=g.Ya("Trident")||g.Ya("MSIE");g.Gc=g.Ya("Edge");g.ug=g.Gc||g.x;g.Fc=g.Ya("Gecko")&&!(g.xa(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge"))&&!(g.Ya("Trident")||g.Ya("MSIE"))&&!g.Ya("Edge");g.Hc=g.xa(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge");g.Hc&&g.Ya("Mobile");g.Xe=g.Ya("Macintosh");g.We=g.Ya("Windows");g.mba=g.Ya("Linux")||g.Ya("CrOS");vg=g.da.navigator||null;vg&&g.xa(vg.appVersion||"","X11");g.nba=g.Ya("Android");g.oba=g.Ec();g.pba=g.Ya("iPad");
g.Kc=function(){if(g.xe&&g.da.opera){var a;var b=g.da.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=vaa())&&(a=b?b[1]:"");return g.x&&(b=Ic(),b>(0,window.parseFloat)(a))?String(b):a}();
Jc={};wg=g.da.document;g.Mc=wg&&g.x?Ic()||("CSS1Compat"==wg.compatMode?(0,window.parseInt)(g.Kc,10):5):void 0;var waa;waa=!g.x||g.Nc(9);g.qba=!g.Fc&&!g.x||g.x&&g.Nc(9)||g.Fc&&g.Lc("1.9.1");g.xg=g.x&&!g.Lc("9");g.rba=g.x||g.xe||g.Hc;g.sba=g.x&&!g.Nc(9);var Qc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};g.yg="StopIteration"in g.da?g.da.StopIteration:{message:"StopIteration",stack:""};g.gd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;var sd={},Baa=0,tba=g.m("yt.net.ping.workerUrl_")||null;g.l("yt.net.ping.workerUrl_",tba,void 0);g.td.prototype.Yb=g.ba(2);g.ud.prototype.toString=function(){return this.topic};var uba=g.m("yt.pubsub2.instance_")||new g.tb;g.tb.prototype.subscribe=g.tb.prototype.subscribe;g.tb.prototype.unsubscribeByKey=g.tb.prototype.xd;g.tb.prototype.publish=g.tb.prototype.na;g.tb.prototype.clear=g.tb.prototype.clear;g.l("yt.pubsub2.instance_",uba,void 0);g.zg=g.m("yt.pubsub2.subscribedKeys_")||{};g.l("yt.pubsub2.subscribedKeys_",g.zg,void 0);g.Ag=g.m("yt.pubsub2.topicToKeys_")||{};g.l("yt.pubsub2.topicToKeys_",g.Ag,void 0);g.Bg=g.m("yt.pubsub2.isAsync_")||{};
g.l("yt.pubsub2.isAsync_",g.Bg,void 0);g.l("yt.pubsub2.skipSubKey_",null,void 0);g.q(xd,g.td);var Eaa=new g.ud("timing-sent",xd);var Kd=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},Caa=(0,g.p)(Kd.clearResourceTimings||Kd.webkitClearResourceTimings||Kd.mozClearResourceTimings||Kd.msClearResourceTimings||Kd.oClearResourceTimings||g.fa,Kd),Ad=Kd.mark?function(a){Kd.mark(a)}:g.fa;g.vba=g.Hc?"webkit":g.Fc?"moz":g.x?"ms":g.xe?"o":"";g.Cg=g.m("yt.dom.getNextId_");if(!g.Cg){g.Cg=function(){return++wba};
g.l("yt.dom.getNextId_",g.Cg,void 0);var wba=0};g.Xd.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.Xd.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.Xd.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Gaa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.Yd=g.m("yt.events.listeners_")||{};g.l("yt.events.listeners_",g.Yd,void 0);var $d=g.m("yt.events.counter_")||{count:0};g.l("yt.events.counter_",$d,void 0);var Haa={enablejsapi:1},Iaa={},Jaa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};ee.prototype.clone=function(){var a=new ee,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ha(c)?a[b]=g.Ua(c):a[b]=c}return a};g.ge=null;g.me=/\s*;\s*/;g.f=g.le.prototype;g.f.isEnabled=function(){return window.navigator.cookieEnabled};
g.f.set=function(a,b,c,d,e,h){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";h=h?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.zd)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+h};
g.f.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.me),e=0,h;h=d[e];e++){if(0==h.lastIndexOf(c,0))return h.substr(c.length);if(h==a)return""}return b};
g.f.remove=function(a,b,c){var d=g.ca(this.get(a));this.set(a,"",0,b,c);return d};
g.f.Rb=g.ba(3);g.f.tb=g.ba(4);g.f.isEmpty=function(){return!this.A.cookie};
g.f.rb=g.ba(0);g.f.re=g.ba(5);g.f.clear=function(){for(var a=g.ne(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.oe=new g.le(window.document);g.oe.B=3950;g.f=g.Ae.prototype;g.f.getHeight=function(){return this.bottom-this.top};
g.f.clone=function(){return new g.Ae(this.top,this.right,this.bottom,this.left)};
g.f.contains=function(a){return g.Be(this,a)};
g.f.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.f.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.f.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.f.scale=function(a,b){var c=g.ma(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Ce;Ce={};g.Dg=g.Fc?"MozUserSelect":g.Hc||g.Gc?"WebkitUserSelect":null;g.hf=g.Ya("Firefox");g.Eg=g.Ec()||g.Ya("iPod");g.Fg=g.Ya("iPad");g.xba=g.Ya("Android")&&!($a()||g.Ya("Firefox")||Za()||g.Ya("Silk"));g.Gg=$a();g.Hg=g.Ya("Safari")&&!($a()||g.Ya("Coast")||Za()||g.Ya("Edge")||g.Ya("Silk")||g.Ya("Android"))&&!(g.Ec()||g.Ya("iPad")||g.Ya("iPod"));g.ga(g.Ke);g.Je=g.m("yt.prefs.UserPrefs.prefs_")||{};g.l("yt.prefs.UserPrefs.prefs_",g.Je,void 0);g.f=g.Ke.prototype;g.f.get=function(a,b){Me(a);Le(a);var c=void 0!==g.Je[a]?g.Je[a].toString():null;return null!=c?c:b?b:""};
g.f.set=function(a,b){Me(a);Le(a);if(null==b)throw"ExpectedNotNull";g.Je[a]=b.toString()};
g.f.remove=function(a){Me(a);Le(a);delete g.Je[a]};
g.f.save=function(){var a;a=[];for(var b in g.Je)a.push(b+"="+(0,window.escape)(g.Je[b]));a=a.join("&");g.pe("PREF",a,63072E3)};
g.f.clear=function(){g.Je={}};g.Ig=g.Oa(function(){if(g.x)return g.Lc("10.0");var a=window.document.createElement("DIV"),b=g.ze(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");g.vc(a,g.tc("div",{style:c}));return""!=g.Ee(a.firstChild,"transition")});g.ga(g.Te);g.Te.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Naa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var of;var Jg=g.Xa,Jg=Jg.toLowerCase();if(g.xa(Jg,"android")){var Kg=Jg.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Kg)of=Number(Kg[1]);else{var Lg={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Mg=Jg.match("("+g.Qa(Lg).join("|")+")");of=Mg?Lg[Mg[0]]:0}}else of=void 0;var Oaa=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],Paa=['audio/mp4; codecs="mp4a.40.2"'];g.q(g.df,g.pb);g.df.prototype.Xa=g.ba(6);g.df.prototype.W=function(){ff(this);g.df.N.W.call(this)};var Qaa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"drm.unavailable":5};g.q(jf,g.pb);var Raa=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.f=jf.prototype;g.f.getId=function(){return this.aa};
g.f.$n=function(a,b){this.isDisposed()||(lf(this,a),b||qf(this),sf(this,b),this.P&&mf(this))};
g.f.ty=function(){return this.xb};
g.f.KM=function(){if(!this.ka){var a=pf(this);a&&"html5"==vf(this)?(this.G="html5",this.P||this.Jg()):(wf(this),this.G="html5",a&&this.T?(this.F.appendChild(this.T),this.Jg()):(this.A.loaded=!0,this.ia=(0,g.p)(function(){var a=this.F,c=this.A.clone();g.m("yt.player.Application.create")(a,c);this.Jg()},this),this.ka=!0,a?this.ia():(g.Bc(this.A.assets.js,this.ia),g.cf(this.A.assets.css))))}};
g.f.JM=function(){var a=this.A.clone();if(!this.L){var b=rf(this);b&&(this.L=window.document.createElement("span"),this.L.tabIndex=0,ef(this.qa,this.L,"focus",this.Ts),this.J=window.document.createElement("span"),this.J.tabIndex=0,ef(this.qa,this.J,"focus",this.Ts),g.$c(this.L,b),g.ad(this.J,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==vf(this)?(this.G="flash",this.P||bf(a,!1,(0,g.p)(this.Jg,this))):(wf(this),this.G="flash",this.A.loaded=!0,g.af(this.F,a),
this.Jg())};
g.f.Ts=function(){rf(this).focus()};
g.f.Jg=function(){if(!this.isDisposed()){var a=rf(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(h){}if(b)if(this.ka=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))tf(this);else{gf(this);this.P=!0;a=rf(this);a.addEventListener&&(this.Y=uf(this,a,"addEventListener"));a.removeEventListener&&(this.ab=uf(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.B[d]||(this.B[d]=uf(this,a,
d))}for(var e in this.D)this.Y(e,this.D[e]);mf(this);this.eb&&this.eb(this.B);this.ga.na("onReady",this.B)}else this.Ub=g.yb((0,g.p)(this.Jg,this),50)}};
g.f.YM=function(){return this.P};
g.f.le=function(a,b){if(!this.isDisposed()){var c=kf(this,b);if(c){if(!g.Ia(this.tc,a)&&!this.D[a]){var d=Saa(this,a);this.Y&&this.Y(a,d)}this.ga.subscribe(a,c);"onReady"==a&&this.P&&g.yb(g.ra(c,this.B),0)}}};
g.f.aL=function(a,b){if(!this.isDisposed()){var c=kf(this,b);c&&this.ga.unsubscribe(a,c)}};
g.f.Fx=function(a){a=a?zaa:yaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.L||b==this.J||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.f.Eo=function(a){g.v("a11y-announce",a)};
g.f.pH=function(a){tf(this,a)};
g.f.tH=function(a){g.v("WATCH_LATER_VIDEO_ADDED",a)};
g.f.uH=function(a){g.v("WATCH_LATER_VIDEO_REMOVED",a)};
g.f.YG=function(){this.qb||(g.Gg?(this.lb=g.Tc(window.document),ef(this.O,window,"scroll",this.oJ),ef(this.O,this.F,"touchmove",this.XI)):(ef(this.O,this.F,"mousewheel",this.jt),ef(this.O,this.F,"wheel",this.jt)),this.qb=!0)};
g.f.ZG=function(){ff(this.O);this.qb=!1};
g.f.jt=function(a){g.ae(a)};
g.f.oJ=function(){window.scrollTo(this.lb.x,this.lb.y)};
g.f.XI=function(a){a.preventDefault()};
g.f.LM=function(){wf(this);this.G="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.A.messages.player_fallback||a;a=g.y("player-unavailable");g.y("unavailable-submessage")&&a&&(g.y("unavailable-submessage").innerHTML=b,(b=g.z("icon",a))&&g.yc(b,"icon")&&(b.src=g.w(b,"icon")),g.Ie(a,!0),g.D(g.y("player"),"off-screen-trigger"))};
g.f.dz=function(){return this.G||vf(this)};
g.f.Py=function(){return this.Ib};
g.f.cancel=function(){this.ia&&g.Cc(this.A.assets.js,this.ia);g.Ab(this.Ub);this.ka=!1};
g.f.W=function(){wf(this);if(this.T&&this.A&&this.A.args.fflags&&-1!=this.A.args.fflags.indexOf("new_html5_dispose=true"))try{this.T.destroy()}catch(b){g.Cb(b)}this.gb=null;for(var a in this.D)g.da[this.D[a]]=null;this.B=null;delete this.F;delete this.X;this.A&&(this.xb=this.A=this.A.fallback=null);jf.N.W.call(this)};g.yf={};g.xf="player_uid_"+(1E9*Math.random()>>>0);var yba=g.m("yt.abuse.botguardInitialized")||he;g.l("yt.abuse.botguardInitialized",yba,void 0);var zba=g.m("yt.abuse.invokeBotguard")||g.ie;g.l("yt.abuse.invokeBotguard",zba,void 0);var Aba=g.m("yt.abuse.dclkstatus.checkDclkStatus")||je;g.l("yt.abuse.dclkstatus.checkDclkStatus",Aba,void 0);var Bba=g.m("yt.player.exports.navigate")||g.we;g.l("yt.player.exports.navigate",Bba,void 0);var Cba=g.m("yt.player.embed")||g.zf;g.l("yt.player.embed",Cba,void 0);var Dba=g.m("yt.player.getPlayerByElement")||g.Af;
g.l("yt.player.getPlayerByElement",Dba,void 0);var Eba=g.m("yt.util.activity.init")||g.ce;g.l("yt.util.activity.init",Eba,void 0);var Fba=g.m("yt.util.activity.getTimeSinceActive")||g.de;g.l("yt.util.activity.getTimeSinceActive",Fba,void 0);var Gba=g.m("yt.util.activity.setTimestamp")||be;g.l("yt.util.activity.setTimestamp",Gba,void 0);var Df,If;g.Hf=null;If="";var Mf=[];var Of,eg,dg,Qf,Pf,eba,Yaa,aba,Zaa,$aa,$f;Qf=0;Pf=0;eba=["server_prefetched_vast","vmap"];Yaa=[900,60,"waiting"];aba=[500,99,"waiting"];Zaa=[300,60,"waiting"];$aa=[400,99,"waiting"];$f=[300,101,"done"];window.yt=window.yt||{};g.l("yt.setConfig",g.wb,void 0);g.l("yt.getConfig",g.t,void 0);g.l("yt.hasMsg",g.Eb,void 0);g.l("yt.pubsub.publish",g.v,void 0);g.l("yt.pubsub.subscribe",g.Lb,void 0);g.l("yt.setMsg",function(a){ub(g.Db,arguments)},void 0);
g.l("yt.setGoogMsg",function(a){ub(g.Db,arguments)},void 0);
g.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var h in b)"_"!=h.charAt(0)&&(c[h]=b[h]);a=g.t("TIMING_INFO",{});"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);Md(c)},void 0);
g.l("ytcsi.tick",g.Cd,void 0);g.q(fg,g.Tb);
fg.prototype.enable=function(){window.onload=Vaa;window.onunload=Waa;window.onerror=Xaa;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",Sf),window.addEventListener("spfpartprocess",Wf),window.addEventListener("spfpartdone",Xf),window.addEventListener("spfprocess",Yf),window.addEventListener("spfdone",ag),window.addEventListener("spferror",bg),window.addEventListener("spfreload",cg),window.addEventListener("spfjsbeforeunload",gg)),a.config=a.config||
{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",cba),this.subscribe("dispose",dba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
fg.prototype.init=function(){fg.N.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.t("PAGEFRAME_JS")?(b=g.t("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.m("ytbin.www.pageframe.setup")()}):a&&(a=g.m("yt.www.masthead.loadSearchbox"))&&a();
var a=g.t("JS_COMMON_MODULE"),d=g.t("JS_PAGE_MODULES");d||(d=[a]);a=g.t("JS_DELAY_LOAD",0);0<a?(g.Ab(this.C),this.C=g.yb(function(){b&&g.Bc(b,c);window.spf.script.require(d)},a)):(b&&g.Bc(b,c),window.spf.script.require(d));
Uaa();g.l("yt.timing.ready_",!0,void 0);Bd(!1);var a=!!g.m("yt.reactLoaded"),e=g.t("REACT_JS",void 0);!a&&e&&g.Bc(e,function(){g.l("yt.reactLoaded",!0,void 0)})};
fg.prototype.dispose=function(){g.Ab(this.C);var a=g.m("ytbin.www.pageframe.cancelSetup");a&&a();g.Bb(Df);if(a=g.Ff())a.removeEventListener("onReady",Ef),a.removeEventListener("onStateChange",Ef);g.l("yt.timing.ready_",!1,void 0);fg.N.dispose.call(this)};
fg.prototype.disable=function(){fg.N.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",Sf),window.removeEventListener("spfpartprocess",Wf),window.removeEventListener("spfpartdone",Xf),window.removeEventListener("spfprocess",Yf),window.removeEventListener("spfdone",ag),window.removeEventListener("spferror",bg),window.removeEventListener("spfreload",cg),window.removeEventListener("spfjsbeforeunload",gg));window.onload=null;window.onunload=null;window.onerror=null};
g.Xb(new fg);})(_yt_www);
